// ═══════════════════════════════════════════════════════════════
// PABLO MONTENEGRO — SITE DATA
// Editar este archivo para actualizar cualquier contenido del sitio.
// ═══════════════════════════════════════════════════════════════

window.SITE = {

  name:     "Pablo Montenegro",
  role:     "Product & Operations Consultant for Founders",
  tagline:  "Over 10 years building payment infrastructure that handles real money at scale.",
  location: "Dublin, Ireland",
  email:    "hello@pablomontenegro.ie",
  linkedin: "https://linkedin.com/in/montenegrofp",
  website:  "https://pablomontenegro.ie",
  cv_url:   "/assets/CV_Pablo_Montenegro.pdf",
  photo:    "/assets/pablo-photo.webp",
  seal:     "/assets/pablo-seal.webp",
  sig:      "/assets/pablo-sig.svg",
  logo:     "/assets/logo.webp",

  hero: {
    headline_en: ["I build what your business runs on.", "<em>Payments, operations and product — untangled and shipped, not just advised on.</em>"],
    headline_es: ["Construyo lo que hace funcionar tu negocio.", "<em>Pagos, operaciones y producto — desenredados y entregados, no solo asesorados.</em>"],
    quote_en: "Over 10 years turning regulated, chaotic or ambiguous operations into products that work — inside a top-5 bank, and from zero for founders who can't wait for a full-time hire. Based in Dublin, working with founders and business owners across Europe and Latin America.",
    quote_es: "Más de 10 años convirtiendo operaciones reguladas, caóticas o ambiguas en productos que funcionan — dentro de un banco top-5, y desde cero para founders que no pueden esperar a contratar full-time. Basado en Dublín, trabajando con founders y dueños de negocio en Europa y América Latina.",
    open_to_en: "Taking on new engagements · Remote · Europe &amp; Latin America",
    open_to_es: "Disponible para nuevos proyectos · Remoto · Europa y Latinoamérica",
  },

  services: {
    tag_en: "How I help", tag_es: "Cómo ayudo",
    h2_en: "Three kinds of <em>hard problems.</em>", h2_es: "Tres tipos de <em>problemas difíciles.</em>",
    sub_en: "Engagements take the shape the problem needs — a short discovery sprint, hands-on implementation, or fractional leadership over a few months. The format follows the work, not the other way around.",
    sub_es: "Los proyectos toman la forma que el problema necesita — un sprint corto de discovery, implementación práctica, o liderazgo fractional durante algunos meses. El formato sigue al trabajo, no al revés.",
    pillars: [
      {
        num: "01",
        title_en: "Untangling regulated, multi-stakeholder products",
        title_es: "Desenredar productos regulados y multi-stakeholder",
        desc_en: "Products where compliance, operations, customer experience and engineering all pull in different directions — and someone has to make the trade-off explicit and shippable.",
        desc_es: "Productos donde compliance, operaciones, experiencia de cliente e ingeniería tiran en direcciones distintas — y alguien tiene que hacer el trade-off explícito y entregable.",
        proof_en: "Proof: I redesigned the mandate lifecycle and collections logic for SEPA-equivalent direct debit at a top-5 bank — cut customer complaints 30%, raised the collection rate 15%.",
        proof_es: "Prueba: rediseñé el ciclo de vida de mandatos y la lógica de cobranza para débito directo equivalente a SEPA en un banco top-5 — reduje quejas 30%, subí la tasa de cobro 15%.",
        link_en: "See PAC 2.0 →", link_es: "Ver PAC 2.0 →", link_url: "itau-pac20.html",
      },
      {
        num: "02",
        title_en: "Turning operational chaos into structured, working flows",
        title_es: "Convertir el caos operativo en flujos estructurados",
        desc_en: "Manual, error-prone processes that grew faster than anyone designed for. The fix is rarely more tooling — it's a clear-headed redesign of the workflow itself.",
        desc_es: "Procesos manuales y propensos a error que crecieron más rápido de lo que alguien diseñó. La solución rara vez es más herramientas — es un rediseño claro del flujo mismo.",
        proof_en: "Proof: I shipped a full operations system in 7 days for a retailer scaling through TikTok Live — replacing manual chaos with structured checkout, inventory and reconciliation flows at zero tooling cost.",
        proof_es: "Prueba: entregué un sistema operativo completo en 7 días para un retailer que escalaba por TikTok Live — reemplazando el caos manual con flujos estructurados de cobro, inventario y reconciliación, sin costo de herramientas.",
        link_en: "See the Karigab → Órbita OS case →", link_es: "Ver el caso Karigab → Órbita OS →", link_url: "karigab-case-study.html",
      },
      {
        num: "03",
        title_en: "0-to-1 discovery for ambiguous, unproven markets",
        title_es: "Discovery 0 a 1 para mercados ambiguos",
        desc_en: "Before a roadmap makes sense, someone needs to find out what's actually true — what users need, what's worth building, and what isn't. Research-led, not assumption-led.",
        desc_es: "Antes de que un roadmap tenga sentido, alguien necesita averiguar qué es realmente cierto — qué necesitan los usuarios, qué vale la pena construir y qué no. Guiado por investigación, no por suposiciones.",
        proof_en: "Proof: I led full discovery for a personal finance app — 34 interviews across 3 countries, MVP scope, a 60-screen prototype, 98% usability success rate. I also validated the core safety hypothesis for a community cycling platform with 40 pilot users in Buenos Aires.",
        proof_es: "Prueba: lideré el discovery completo para una app de finanzas personales — 34 entrevistas en 3 países, scope de MVP, prototipo de 60 pantallas, 98% de éxito en usabilidad. También validé la hipótesis central de seguridad para una plataforma comunitaria de ciclismo con 40 usuarios piloto en Buenos Aires.",
        link_en: "See the discovery case →", link_es: "Ver el caso de discovery →", link_url: "monevol-case-study.html",
      },
    ],
    cta_en: "Tell me about your problem →", cta_es: "Cuéntame tu problema →",
  },

  engagements: {
    tag_en: "Ways to work together", tag_es: "Formas de trabajar juntos",
    h2_en: "Three engagement <em>models.</em>", h2_es: "Tres modelos de <em>colaboración.</em>",
    sub_en: "The format follows the problem, not the other way around. Each model below maps to a type of need — pick the one that fits, or use the conversation to figure out which one applies.",
    sub_es: "El formato sigue al problema, no al revés. Cada modelo abajo corresponde a un tipo de necesidad — elige el que calce, o usa la conversación inicial para definir cuál aplica.",
    packages: [
      {
        num: "01",
        name_en: "Discovery Sprint", name_es: "Discovery Sprint",
        duration_en: "2 weeks", duration_es: "2 semanas",
        for_en: "When you need to validate a hypothesis before committing real budget.",
        for_es: "Cuando necesitas validar una hipótesis antes de comprometer presupuesto real.",
        includes_en: [
          "Structured interviews or stakeholder sessions",
          "A clear problem definition — what's actually true, not assumed",
          "Scope recommendation: build, don't build, or investigate further",
        ],
        includes_es: [
          "Entrevistas estructuradas o sesiones con stakeholders",
          "Una definición clara del problema — qué es realmente cierto, no asumido",
          "Recomendación de alcance: construir, no construir, o seguir investigando",
        ],
        proof_en: "Proof: this is the format behind Monevol's 34-interview discovery and CycleSafe's safety hypothesis validation.",
        proof_es: "Prueba: este es el formato detrás del discovery de 34 entrevistas de Monevol y la validación de la hipótesis de seguridad de CycleSafe.",
      },
      {
        num: "02",
        name_en: "Operational Redesign Engagement", name_es: "Operational Redesign Engagement",
        duration_en: "4–8 weeks", duration_es: "4–8 semanas",
        for_en: "When a specific payment, collections or operational flow is breaking under its own volume.",
        for_es: "Cuando un flujo específico de pagos, cobranza u operaciones se está rompiendo por su propio volumen.",
        includes_en: [
          "Audit of the current flow — where time, trust or money leaks",
          "Redesigned process with the trade-offs made explicit",
          "Working prototype or implementation-ready spec, plus a measured before/after",
        ],
        includes_es: [
          "Auditoría del flujo actual — dónde se filtra tiempo, confianza o dinero",
          "Proceso rediseñado con los trade-offs explícitos",
          "Prototipo funcional o especificación lista para implementar, más medición antes/después",
        ],
        proof_en: "Proof: this format produced the Karigab → Órbita OS story (constraint-first system in 7 days, −85% workload; now a live multi-tenant SaaS) and the mandate lifecycle rebuild at a top-5 bank (−30% complaints, +15% collection rate).",
        proof_es: "Prueba: este formato produjo el arco Karigab → Órbita OS (sistema por restricción en 7 días, −85% carga; ahora SaaS multi-tenant en producción) y el rediseño del ciclo de vida de mandatos en un banco top-5 (−30% quejas, +15% tasa de cobro).",
      },
      {
        num: "03",
        name_en: "Fractional Product Leadership", name_es: "Fractional Product Leadership",
        duration_en: "From 3 months, 10–20h/week", duration_es: "Desde 3 meses, 10–20h/semana",
        for_en: "When the need isn't a single project but ongoing senior judgment — without a full-time hire.",
        for_es: "Cuando la necesidad no es un proyecto puntual sino criterio senior continuo — sin contratar full-time.",
        includes_en: [
          "Embedded product leadership — roadmap, prioritisation, stakeholder alignment",
          "Direct involvement in delivery, not just advisory recommendations",
          "Flexible scope, reviewed and adjusted as the engagement evolves",
        ],
        includes_es: [
          "Liderazgo de producto integrado — roadmap, priorización, alineación de stakeholders",
          "Involucramiento directo en la entrega, no solo recomendaciones de asesoría",
          "Alcance flexible, revisado y ajustado a medida que avanza el proyecto",
        ],
        proof_en: "Proof: 10+ years leading product end-to-end inside regulated, multi-stakeholder organisations — not just advising from the outside.",
        proof_es: "Prueba: 10+ años liderando producto end-to-end dentro de organizaciones reguladas y multi-stakeholder — no solo asesorando desde afuera.",
      },
    ],
    note_en: "Pricing depends on scope and is discussed directly — these are the shapes engagements typically take, not fixed quotes.",
    note_es: "El precio depende del alcance y se discute directamente — estas son las formas que suelen tomar los proyectos, no cotizaciones fijas.",
    cta_en: "Tell me about your problem →", cta_es: "Cuéntame tu problema →",
  },

  metrics: [
    { num: "10+",  label_en: "Years · Payments & Banking",  label_es: "Años · Pagos y Banca" },
    { num: "~70%", label_en: "Mandate adoption · ePAC",     label_es: "Adopción de mandatos · ePAC" },
    { num: "−30%", label_en: "Complaints reduced · PAC 2.0",label_es: "Quejas reducidas · PAC 2.0" },
    { num: "10",   label_en: "Initiatives delivered",       label_es: "Iniciativas entregadas" },
  ],

  consulting: {
    label_en: "Independent Consulting · 2024–Present",
    label_es: "Consultoría Independiente · 2024–Presente",
    desc_en:  "Four engagements across healthtech operations, payment operations, product design, and urban mobility — scoped, delivered and measured independently.",
    desc_es:  "Cuatro proyectos en operaciones healthtech, operaciones de pago, diseño de producto y movilidad urbana — definidos, entregados y medidos de forma independiente.",
    cases: [
      {
        id: "dermoskin", num: "01", year: "2026",
        tag_en:   "Practice Management · Healthtech · SaaS",
        tag_es:   "Gestión de Consultorio · Healthtech · SaaS",
        title_en: "<em>DermoSkin</em> — From clinic system to Filum",
        title_es: "<em>DermoSkin</em> — De sistema de clínica a Filum",
        desc_en:  "Built the full operating system for a dermatology clinic — patient records with contraindication alerts, scheduling, informed-consent workflows, financial control and WhatsApp-based follow-ups — replacing scattered notebooks and spreadsheets. What it proved about running a regulated, appointment-based practice became the starting point for Filum, a multi-tenant SaaS now in development.",
        desc_es:  "Construí el sistema operativo completo para una clínica de dermatología — fichas de pacientes con alertas de contraindicación, agenda, consentimiento informado, control financiero y seguimiento por WhatsApp — reemplazando cuadernos y planillas dispersas. Lo que ese sistema demostró sobre operar una práctica regulada y basada en citas se convirtió en el punto de partida de Filum, un SaaS multi-tenant ahora en desarrollo.",
        sepa_en:  "≈ Practice management · patient records · healthtech operations",
        sepa_es:  "≈ Gestión de consultorio · fichas de pacientes · operaciones healthtech",
        metrics:  [
          { num: "1",   label_en: "Live clinic operating on the system", label_es: "Clínica en producción con el sistema" },
          { num: "6",   label_en: "Modules — patients to finance",        label_es: "Módulos — pacientes a finanzas" },
          { num: "→",   label_en: "Now evolving into Filum (SaaS)",       label_es: "Ahora evoluciona a Filum (SaaS)" },
        ],
        cta_en: "Full case study →", cta_es: "Caso completo →",
        cta_url: "dermoskin-case-study.html", vis_type: "dermoskin",
      },
      {
        id: "monevol", num: "02", year: "2024", advisory: true,
        tag_en:   "Product Strategy · UX Research · Personal Finance",
        tag_es:   "Estrategia de Producto · Investigación UX · Finanzas Personales",
        title_en: "Monevol <em>360</em>",
        title_es: "Monevol <em>360</em>",
        desc_en:  "End-to-end product design for a personal finance app targeting underserved users in LatAm. Led full discovery: 34 user interviews across 3 countries, competitive benchmarking, card sorting, MVP scope and 60-screen prototype. Core finding: users needed visibility, not more features.",
        desc_es:  "Diseño de producto end-to-end para una app de finanzas personales dirigida a usuarios desatendidos en LatAm. Lideré el discovery completo: 34 entrevistas en 3 países, benchmarking competitivo, card sorting, scope del MVP y prototipo de 60 pantallas. Hallazgo central: los usuarios necesitaban visibilidad, no más funcionalidades.",
        sepa_en:  "≈ Consumer fintech · payment UX · product strategy",
        sepa_es:  "≈ Fintech consumer · UX de pagos · estrategia de producto",
        metrics:  [
          { num: "98%", label_en: "Usability success rate",  label_es: "Tasa de éxito en usabilidad" },
          { num: "34",  label_en: "User interviews",         label_es: "Entrevistas de usuario" },
          { num: "60+", label_en: "Prototype screens",       label_es: "Pantallas del prototipo" },
        ],
        cta_en: "Full case study →", cta_es: "Caso completo →",
        cta_url: "monevol-case-study.html", vis_type: "monevol",
      },
      /*
      {
        id: "remesas", num: "TBD", year: "2026",
        tag_en:   "Payment Operations · Cross-Border · Workflow Design",
        tag_es:   "Operaciones de Pago · Internacional · Diseño de Flujos",
        title_en: "Cross-Border <em>Payment Operations</em>",
        title_es: "Operaciones de Pago <em>Internacionales</em>",
        desc_en:  "Redesigned client onboarding, transaction tracking, payout controls and reconciliation workflows for a small Europe–Bolivia transfer service. Replaced manual error-prone processes with structured operational flows. Reduced verification workload by 70% at zero tooling cost.",
        desc_es:  "Rediseño de onboarding de clientes, seguimiento de transacciones, controles de pago y flujos de reconciliación para un servicio de transferencias Europa–Bolivia. Reemplazó procesos manuales propensos a errores con flujos operativos estructurados. Redujo la carga de verificación en un 70% sin costo de herramientas.",
        sepa_en:  "≈ Cross-border payment ops · reconciliation · workflow design",
        sepa_es:  "≈ Operaciones de pago internacional · reconciliación · diseño de flujos",
        metrics:  [
          { num: "−70%", label_en: "Verification workload",  label_es: "Carga de verificación" },
          { num: "100%", label_en: "Transactions traceable", label_es: "Transacciones trazables" },
          { num: "€0",   label_en: "Tooling cost",           label_es: "Costo de herramientas" },
        ],
        cta_en: "Full case study →", cta_es: "Caso completo →",
        cta_url: "case-remesas-portfolio.html", vis_type: "remesas",
      },
      */
      {
        id: "karigab", num: "03", year: "2025–2026",
        tag_en:   "Operations Design · Social Commerce · SaaS",
        tag_es:   "Diseño Operativo · Social Commerce · SaaS",
        title_en: "<em>Karigab → Órbita OS</em> — From spreadsheet to SaaS",
        title_es: "<em>Karigab → Órbita OS</em> — De planilla a SaaS",
        desc_en:  "A constraint-first operations system — WhatsApp + Google Sheets, delivered in 7 days, −85% workload, Bs.0 cost — became the validated thesis for Órbita OS: a multi-tenant SaaS platform for social commerce retail, now live with its first pilot client.",
        desc_es:  "Un sistema operativo por restricción — WhatsApp + Google Sheets, entregado en 7 días, −85% carga, Bs.0 costo — se convirtió en la tesis validada para Órbita OS: una plataforma SaaS multi-tenant para retail de social commerce, ahora en producción con su primer cliente piloto.",
        sepa_en:  "≈ Operations design · social commerce · SaaS · product",
        sepa_es:  "≈ Diseño operativo · social commerce · SaaS · producto",
        metrics:  [
          { num: "−85%", label_en: "Operational workload · Phase 1", label_es: "Carga operativa · Fase 1" },
          { num: "7d",   label_en: "Phase 1 delivery",               label_es: "Entrega Fase 1" },
          { num: "1",    label_en: "Live SaaS pilot · Órbita OS",    label_es: "Piloto SaaS · Órbita OS" },
        ],
        cta_en: "Full case study →", cta_es: "Caso completo →",
        cta_url: "karigab-case-study.html", vis_type: "karigab",
      },
      {
        id: "cyclesafe", num: "04", year: "2024–2025", advisory: true,
        tag_en:   "Urban Mobility · Community Product · React Native",
        tag_es:   "Movilidad Urbana · Producto Comunitario · React Native",
        title_en: "<em>CycleSafe</em> — Community Safety Map",
        title_es: "<em>CycleSafe</em> — Mapa Comunitario de Seguridad",
        desc_en:  "Led product from discovery to pilot for a community-powered cycling safety platform in Buenos Aires. Cyclists share real-time route safety data — ciclovías, mixed streets, risk zones — filling the gap that Google Maps and Strava leave. 40 pilot users. Core hypothesis validated: safety is a primary routing criterion. Paused at scale due to relocation to Ireland.",
        desc_es:  "Lideré el producto desde el discovery hasta el piloto para una plataforma de seguridad ciclista impulsada por la comunidad en Buenos Aires. Los ciclistas comparten datos de seguridad en tiempo real — ciclovías, calles mixtas, zonas de riesgo — cubriendo el vacío que dejan Google Maps y Strava. 40 usuarios piloto. Hipótesis central validada: la seguridad es un criterio primario de ruta. Pausado en fase de escala por traslado a Irlanda.",
        sepa_en:  "≈ Community platforms · network effects · mobile product · 0-to-1",
        sepa_es:  "≈ Plataformas comunitarias · efectos de red · producto móvil · 0 a 1",
        metrics:  [
          { num: "40",    label_en: "Pilot users · Buenos Aires", label_es: "Usuarios piloto · Buenos Aires" },
          { num: "React", label_en: "Native · mobile-first stack", label_es: "Native · stack mobile-first" },
          { num: "✓",     label_en: "Safety hypothesis validated", label_es: "Hipótesis de seguridad validada" },
        ],
        cta_en: "Full case study →", cta_es: "Caso completo →",
        cta_url: "cyclesafe-case-study.html", vis_type: "cyclesafe",
      },
    ],
  },

  itau: {
    label_en: "Itaú Bank Chile · 2017–2024",
    label_es: "Itaú Bank Chile · 2017–2024",
    desc_en:  "7 years as Senior PM owning the payments and collections roadmap at Chile's largest private bank. Delivered across infrastructure, recurring collections, mandate digitisation, H2H integrations and operational tooling — in a regulated, enterprise-scale environment.",
    desc_es:  "7 años como Senior PM responsable del roadmap de pagos y cobranza en el banco privado más grande de Chile. Entregué en infraestructura, cobranza recurrente, digitalización de mandatos, integraciones H2H y herramientas operacionales — en un entorno regulado a escala empresarial.",
    cases: [
      {
        id: "pac", num: "04", year: "2021–2022",
        tag_en:   "Collections Platform · Itaú Bank",
        tag_es:   "Plataforma de Cobranza · Itaú Bank",
        title_en: "PAC 2.0 — Automated <em>Collections</em>",
        title_es: "PAC 2.0 — Cobranza <em>Automatizada</em>",
        desc_en:  "Recurring collections failed silently — no retry logic, no failure classification, problems surfaced through complaints. Redesigned the full lifecycle: failure taxonomy, retry logic, operational dashboard and monitoring. Led discovery, API design and phased rollout.",
        desc_es:  "Los cobros recurrentes fallaban en silencio — sin lógica de reintento, sin clasificación de fallas, los problemas surgían por quejas. Rediseñé el ciclo completo: taxonomía de fallas, lógica de reintento, dashboard operacional y monitoreo. Lideré discovery, diseño de API y rollout por fases.",
        sepa_en:  "≈ SEPA Direct Debit · R-message management · collections intelligence",
        sepa_es:  "≈ SEPA Direct Debit · gestión de R-messages · inteligencia de cobranza",
        metrics:  [
          { num: "−30%", label_en: "Customer complaints",    label_es: "Quejas de clientes" },
          { num: "+20%", label_en: "Operational efficiency",  label_es: "Eficiencia operacional" },
          { num: "+15%", label_en: "Collection rate",         label_es: "Tasa de cobro" },
        ],
        cta_en: "Full case study →", cta_es: "Caso completo →",
        cta_url: "itau-pac20.html", vis_type: "pac",
      },
      {
        id: "qr", num: "05", year: "2022–2023",
        tag_en:   "Payment UX · QR Interoperability · Itaú Bank",
        tag_es:   "UX de Pagos · Interoperabilidad QR · Itaú Bank",
        title_en: "QR Interoperability <em>Redesign</em>",
        title_es: "Rediseño de <em>Interoperabilidad QR</em>",
        desc_en:  "Users abandoned at specific steps. Error states confirmed failure without explaining what or why. Mapped every drop-off, ran usability testing, benchmarked against PIX. Redesigned the error language and flow — not just the layout.",
        desc_es:  "Los usuarios abandonaban en pasos específicos. Los estados de error confirmaban la falla sin explicar qué ni por qué. Mapeé cada punto de abandono, realicé pruebas de usabilidad y benchmarking con PIX. Rediseñé el lenguaje de errores y el flujo — no solo la interfaz.",
        sepa_en:  "≈ PIX · Bizum · SEPA Instant · payment flow UX",
        sepa_es:  "≈ PIX · Bizum · SEPA Instant · UX de flujos de pago",
        metrics:  [
          { num: "+25%", label_en: "Digital payment adoption", label_es: "Adopción de pago digital" },
        ],
        cta_en: null, vis_type: "qr",
      },
      {
        id: "epac", num: "06", year: "2021–2022",
        tag_en:   "Mandate Digitisation · Direct Debit · Itaú Bank",
        tag_es:   "Digitalización de Mandatos · Débito Directo · Itaú Bank",
        title_en: "ePAC — Digital <em>Direct Debit</em>",
        title_es: "ePAC — Débito Directo <em>Digital</em>",
        desc_en:  "A 45-day paper mandate process was blocking recurring payment adoption before it started. Led product definition and Forpay partnership to deliver a fully digital mandate platform — reducing activation from weeks to 24 hours.",
        desc_es:  "Un proceso de mandato en papel de 45 días bloqueaba la adopción de pagos recurrentes antes de comenzar. Lideré la definición del producto y la alianza con Forpay para una plataforma de mandatos 100% digital — reduciendo la activación de semanas a 24 horas.",
        sepa_en:  "≈ SEPA mandate e-signature · digital onboarding · recurring payment activation",
        sepa_es:  "≈ Firma electrónica de mandatos SEPA · onboarding digital · activación de pagos recurrentes",
        metrics:  [
          { num: "45d→24h", label_en: "Activation time",     label_es: "Tiempo de activación" },
          { num: "~70%",    label_en: "Customer adoption",    label_es: "Adopción de clientes" },
          { num: "3 mo",    label_en: "End-to-end delivery",  label_es: "Entrega end-to-end" },
        ],
        cta_en: "Full case study →", cta_es: "Caso completo →",
        cta_url: "itau-epac.html", vis_type: "epac",
      },
      {
        id: "multibank", num: "07", year: "2022–2023",
        tag_en:   "B2B Payments · Multi-Bank · Enterprise · Itaú Bank",
        tag_es:   "Pagos B2B · Multibanco · Empresas · Itaú Bank",
        title_en: "Multi-Bank <em>Payment Button</em>",
        title_es: "Botón de Pago <em>Multibanco</em>",
        desc_en:  "Corporate clients needed to receive high-value payments from customers at any Chilean bank without separate integrations per bank. Defined a single access model (API + web portal), led pilot with 3 companies.",
        desc_es:  "Los clientes corporativos necesitaban recibir pagos de alto valor desde cualquier banco chileno sin integraciones separadas por banco. Definí un modelo de acceso único (API + portal web), lideré el piloto con 3 empresas.",
        sepa_en:  "≈ Open Banking payment initiation (PSD2) · B2B payment orchestration",
        sepa_es:  "≈ Iniciación de pagos Open Banking (PSD2) · orquestación de pagos B2B",
        metrics:  [
          { num: "5d→1d",    label_en: "Payment processing", label_es: "Procesamiento de pagos" },
          { num: "CLP 50M+", label_en: "Avg ticket",         label_es: "Ticket promedio" },
          { num: "3 co.",    label_en: "Pilot companies",     label_es: "Empresas piloto" },
        ],
        cta_en: "Full case study →", cta_es: "Caso completo →",
        cta_url: "itau-multibank.html", vis_type: "multibank",
      },
      {
        id: "engine", num: "08", year: "2020–2021",
        tag_en:   "Platform Infrastructure · Notifications · Itaú Bank",
        tag_es:   "Infraestructura · Notificaciones · Itaú Bank",
        title_en: "Bank-Wide <em>Notification Engine</em>",
        title_es: "Motor de <em>Notificaciones</em> Bancario",
        desc_en:  "Legacy system had hard volume limits, no push support and required full rebuild per product. Defined a 3-channel engine (SMS, email, push) with intelligent routing and plug-and-play architecture usable by any team.",
        desc_es:  "El sistema heredado tenía límites de volumen fijos, sin soporte push y requería reconstrucción completa por producto. Definí un motor de 3 canales (SMS, email, push) con enrutamiento inteligente y arquitectura plug-and-play usable por cualquier equipo.",
        sepa_en:  "≈ Payment notification infrastructure · multi-channel delivery",
        sepa_es:  "≈ Infraestructura de notificaciones de pago · entrega multicanal",
        metrics:  [
          { num: "3",  label_en: "Channels unified",    label_es: "Canales unificados" },
          { num: "0",  label_en: "Per-product rebuilds", label_es: "Reconstrucciones por producto" },
        ],
        cta_en: null, vis_type: "engine",
      },
      {
        id: "dashboard", num: "09", year: "2020–2021",
        tag_en:   "Operational Intelligence · Analytics · Itaú Bank",
        tag_es:   "Inteligencia Operacional · Analítica · Itaú Bank",
        title_en: "Collections <em>Monitoring Dashboard</em>",
        title_es: "Dashboard de <em>Monitoreo</em> de Cobranza",
        desc_en:  "Incidents surfaced through complaints — not data. Defined three purpose-built views for three audiences: operations (real-time), commercial (client-level) and product (trends). Reduced incident detection time by 40%.",
        desc_es:  "Los incidentes surgían por quejas, no por datos. Definí tres vistas con propósito específico para tres audiencias: operaciones (tiempo real), comercial (por cliente) y producto (tendencias). Redujo la detección de incidentes en un 40%.",
        sepa_en:  "≈ Payment operations intelligence · SLA monitoring · incident management",
        sepa_es:  "≈ Inteligencia de operaciones de pago · monitoreo de SLA · gestión de incidentes",
        metrics:  [
          { num: "40%", label_en: "Faster incident detection", label_es: "Detección más rápida" },
          { num: "3",   label_en: "Purpose-built views",       label_es: "Vistas especializadas" },
        ],
        cta_en: null, vis_type: "dashboard",
      },
    ],
  },

  products: [
    {
      img: "/assets/prod-1.webp",
      type_en: "Template · Notion / Document",
      type_es: "Plantilla · Notion / Documento",
      title_en: "Fintech Process Documentation Template",
      title_es: "Plantilla de Documentación de Procesos Fintech",
      desc_en: "Standardise how your team documents product decisions, payment flows and operational processes.",
      desc_es: "Estandariza cómo tu equipo documenta decisiones de producto, flujos de pago y procesos operacionales.",
      price: "€19", url: "https://pablomontenegro.gumroad.com/l/vxgcb",
    },
    {
      img: "/assets/prod-2.webp",
      type_en: "Guide · 10 chapters · EN & ES",
      type_es: "Guía · 10 capítulos · EN y ES",
      title_en: "How Payments Actually Work",
      title_es: "Cómo Funcionan Realmente los Pagos",
      desc_en: "A practitioner's guide to payment and collections product management. Written from 10 years of hands-on delivery.",
      desc_es: "Una guía práctica para la gestión de productos de pago y cobranza. Escrita desde 10 años de entrega real.",
      price: "€29", url: "https://pablomontenegro.gumroad.com/l/kqadd",
    },
    {
      img: "/assets/prod-3.webp",
      type_en: "Tool · Excel · EN & ES",
      type_es: "Herramienta · Excel · EN y ES",
      title_en: "Backlog Prioritisation Matrix",
      title_es: "Matriz de Priorización de Backlog",
      desc_en: "Automated weighted scoring model for fintech product teams. 7 decision pillars with MoSCoW filter.",
      desc_es: "Modelo de puntuación ponderada para equipos de producto fintech. 7 pilares de decisión con filtro MoSCoW.",
      price: "€39", url: "https://montenegrofp.gumroad.com/l/BacklogPrioritisationMatrix",
    },
    {
      img: "/assets/prod-4.webp",
      type_en: "Tool · Excel macro · Personal finance",
      type_es: "Herramienta · Macro Excel · Finanzas personales",
      title_en: "Financial Operating System",
      title_es: "Sistema Operativo Financiero",
      desc_en: "Personal finance macro for income, expenses, savings goals and investments. Control without complexity.",
      desc_es: "Macro de finanzas personales para ingresos, gastos, metas de ahorro e inversiones. Control sin complejidad.",
      price: "€19", url: null, coming_soon: true,
    },
  ],

  experience: [
    {
      years: "2024 – Present", company: "Independent Consultant", location: "Dublin, Ireland",
      role_en: "PM Consultant · Payments & Collections",
      role_es: "Consultor PM · Pagos y Cobranza",
      bullets_en: [
        "<strong>Monevol 360 (2024):</strong> Full product lifecycle — 34 user interviews, MVP scope, 60-screen Figma prototype, 98% usability success rate.",
        "<strong>Karigab → Órbita OS (2025–2026):</strong> Constraint-first operations system in WhatsApp + Google Sheets (7 days, −85% workload, Bs.0 cost), then productised as Órbita OS — a multi-tenant SaaS platform now live with Karigab as pilot tenant.",
        "Ongoing: 500+ annotated training data points for an AI model platform — payment and collections use cases, above 95% accuracy.",
      ],
      bullets_es: [
        "<strong>Monevol 360 (2024):</strong> Ciclo completo de producto — 34 entrevistas, scope del MVP, prototipo Figma de 60 pantallas, 98% de tasa de éxito en usabilidad.",
        "<strong>Karigab → Órbita OS (2025–2026):</strong> Sistema operativo por restricción en WhatsApp + Google Sheets (7 días, −85% carga, Bs.0 costo), luego productizado como Órbita OS — plataforma SaaS multi-tenant ahora en producción con Karigab como tenant piloto.",
        "En curso: 500+ puntos de datos de entrenamiento para una plataforma de IA en casos de uso de pagos y cobranza, con precisión superior al 95%.",
      ],
    },
    {
      years: "2017 – 2024", company: "Itaú Bank Chile", location: "Santiago, Chile",
      role_en: "Senior Product Manager · Payments & Collections",
      role_es: "Senior Product Manager · Pagos y Cobranza",
      bullets_en: [
        "<strong>PAC 2.0:</strong> Redesigned recurring collections lifecycle. −30% complaints, +20% operational efficiency, +15%+ collection rate.",
        "<strong>QR Interoperability:</strong> Mapped drop-off, redesigned error flows, benchmarked against PIX. +25% digital payment adoption.",
        "<strong>ePAC — Digital Direct Debit:</strong> Mandate activation from 45 days to 24 hours. ~70% adoption. Delivered in 3 months.",
        "<strong>Multi-Bank Payment Button:</strong> Single integration for high-value corporate payments across Chilean banks. Piloted with 3 companies.",
        "<strong>Notification Engine:</strong> 3-channel (SMS, email, push) with intelligent routing and plug-and-play architecture.",
        "<strong>Collections Dashboard:</strong> 3 purpose-built views for operations, commercial and product. 40% faster incident detection.",
      ],
      bullets_es: [
        "<strong>PAC 2.0:</strong> Rediseño del ciclo de cobranza recurrente. −30% quejas, +20% eficiencia operacional, +15%+ tasa de cobro.",
        "<strong>Interoperabilidad QR:</strong> Mapeé abandono, rediseñé flujos de error, benchmarking con PIX. +25% adopción de pago digital.",
        "<strong>ePAC — Débito Directo Digital:</strong> Activación de mandatos de 45 días a 24 horas. ~70% adopción. Entregado en 3 meses.",
        "<strong>Botón de Pago Multibanco:</strong> Integración única para pagos corporativos en bancos chilenos. Piloteado con 3 empresas.",
        "<strong>Motor de Notificaciones:</strong> 3 canales (SMS, email, push) con enrutamiento inteligente y arquitectura plug-and-play.",
        "<strong>Dashboard de Cobranza:</strong> 3 vistas especializadas para operaciones, comercial y producto. 40% más rápida detección de incidentes.",
      ],
    },
    {
      years: "2016 – 2017", company: "SURA Group Chile", location: "Santiago, Chile",
      role_en: "Business Strategy & Client Success Analyst",
      role_es: "Analista de Estrategia de Negocio y Éxito de Clientes",
      bullets_en: ["Performance dashboards and client retention monitoring for a regulated financial services portfolio."],
      bullets_es: ["Dashboards de desempeño y monitoreo de retención de clientes para una cartera de servicios financieros regulados."],
    },
    {
      years: "2012 – 2016", company: "Santander Bank Chile", location: "Santiago, Chile",
      role_en: "Implementation & Process Supervisor — Corporate Cash Management",
      role_es: "Supervisor de Implementación y Procesos — Cash Management Corporativo",
      bullets_en: ["Onboarding, after-sales and SLA monitoring for corporate payment and treasury operations."],
      bullets_es: ["Onboarding, postventa y monitoreo de SLA para operaciones de pago y tesorería corporativa."],
    },
  ],

  writing: [
    {
      type_en: "Industry Analysis · English", type_es: "Análisis de Mercado · Inglés", year: "2024",
      title_en: "Chile's Open Finance Delay: How the Regulatory Pause Could Set Back Innovation",
      title_es: "El Retraso del Open Finance en Chile: Cómo la Pausa Regulatoria Podría Frenar la Innovación",
      desc_en: "Why Chile's Open Finance framework stalled, what it means for payment infrastructure, and why the market cannot afford to wait.",
      desc_es: "Por qué el marco de Open Finance de Chile se detuvo, qué significa para la infraestructura de pagos y por qué el mercado no puede esperar.",
      url: "https://www.linkedin.com/pulse/chiles-open-finance-delay-how-regulatory-pause-back-why-montenegro-sjrle/",
    },
    {
      type_en: "Market Perspective · English", type_es: "Perspectiva de Mercado · Inglés", year: "2024",
      title_en: "Rethinking How We Move Money in Chile",
      title_es: "Repensando Cómo Movemos el Dinero en Chile",
      desc_en: "A practitioner's view on the gap between what payment technology enables and what Chile's regulatory framework currently permits.",
      desc_es: "La visión de un practicante sobre la brecha entre lo que la tecnología de pagos habilita y lo que el marco regulatorio de Chile permite actualmente.",
      url: "https://www.linkedin.com/pulse/rethinking-how-we-move-money-chile-pablo-montenegro-e042c/",
    },
  ],

  recommendations: [
    {
      quote_en: "He connected business and technical worlds effectively — from definition through to delivery.",
      quote_es: "Conectó los mundos de negocio y técnico de forma efectiva — desde la definición hasta la entrega.",
      full_en: "Pablo played a key role implementing recurring payments and digital collections flows, always focused on improving customer experience and operational efficiency. Very organised in product management, with clarity to prioritise, coordinate teams and take initiatives from definition through to delivery.",
      full_es: "Pablo jugó un papel clave en la implementación de pagos recurrentes y flujos de cobranza digital, siempre enfocado en mejorar la experiencia del cliente y la eficiencia operacional. Muy organizado en la gestión de producto, con claridad para priorizar, coordinar equipos y llevar iniciativas desde la definición hasta la entrega.",
      name: "Ignacio Prieto Gana",
      role_en: "CCO at Forpay · Itaú Bank integration partner",
      role_es: "CCO en Forpay · partner de integración Itaú Bank",
      date: "April 2026", url: "https://linkedin.com/in/montenegrofp",
    },
    {
      quote_en: "His contribution was key — always focused on results and excellent at coordinating product and operations.",
      quote_es: "Su contribución fue clave — siempre enfocado en resultados y excelente coordinando producto y operaciones.",
      full_en: "As Product Owner for Collections, Pablo stood out for his business vision, his ability to lead collaboratively and his skill in transforming requirements into concrete, viable solutions that operations could actually run.",
      full_es: "Como Product Owner de Cobranza, Pablo destacó por su visión de negocio, su capacidad de liderar de forma colaborativa y su habilidad para transformar requisitos en soluciones concretas y viables que operaciones pudiera ejecutar.",
      name: "María del Carmen Bini Mattea",
      role_en: "Head of Cash Management · Itaú Chile",
      role_es: "Jefa de Cash Management · Itaú Chile",
      date: "March 2026", url: "https://linkedin.com/in/montenegrofp",
    },
    {
      quote_en: "Outstanding focus on results. He increased client retention by 35% and raised the bar for how we built collections products.",
      quote_es: "Enfoque sobresaliente en resultados. Aumentó la retención de clientes en un 35% y elevó el estándar de cómo construimos productos de cobranza.",
      full_en: "Pablo worked alongside me for 5 years at Itaú Chile. He consistently connected the strategic product vision with the concrete needs of clients and operations — delivering solutions that were both commercially viable and technically sound.",
      full_es: "Pablo trabajó junto a mí durante 5 años en Itaú Chile. Conectó consistentemente la visión estratégica del producto con las necesidades concretas de clientes y operaciones — entregando soluciones viables comercialmente y técnicamente sólidas.",
      name: "Raúl Hidalgo Figueroa",
      role_en: "Digital Transformation Manager · Itaú Chile",
      role_es: "Gerente de Transformación Digital · Itaú Chile",
      date: "March 2026", url: "https://linkedin.com/in/montenegrofp",
    },
    {
      quote_en: "Professionalism, systematic thinking and consistent delivery — he helped us meet our objectives and differentiate from competition.",
      quote_es: "Profesionalismo, pensamiento sistemático y entrega consistente — nos ayudó a alcanzar nuestros objetivos y diferenciarnos de la competencia.",
      full_en: "Pablo was a member of my team, responsible for developing and innovating collections products while maintaining service continuity. He delivered without disruption.",
      full_es: "Pablo era miembro de mi equipo, responsable del desarrollo e innovación de productos de cobranza mientras mantenía la continuidad del servicio. Entregó sin generar disrupciones.",
      name: "Rodrigo Velásquez Velasco",
      role_en: "Product Strategy Manager · direct manager",
      role_es: "Gerente de Estrategia de Producto · manager directo",
      date: "June 2025", url: "https://linkedin.com/in/montenegrofp",
    },
  ],

  skills: [
    {
      cat_en: "Payments & Banking",
      cat_es: "Pagos y Banca",
      items: ["SEPA Direct Debit", "PSD2", "Open Banking", "Recurring collections", "QR payments", "Mandate management", "R-message codes", "H2H integrations", "STP automation"],
    },
    {
      cat_en: "Product Management",
      cat_es: "Gestión de Producto",
      items: ["Product strategy", "Roadmap ownership", "Discovery", "Backlog prioritisation", "MVP definition", "API product management", "Stakeholder management", "Regulated environments"],
    },
    {
      cat_en: "Technical",
      cat_es: "Técnico",
      items: ["REST APIs", "Payment integrations", "Backend systems", "SQL", "Fraud risk mitigation", "System-to-system flows"],
    },
    {
      cat_en: "Research & Design",
      cat_es: "Investigación y Diseño",
      items: ["Design Thinking", "User research", "Figma", "Information architecture", "Usability testing", "Card sorting"],
    },
    {
      cat_en: "Delivery",
      cat_es: "Entrega",
      items: ["Agile · Scrum", "Cross-functional squads", "Phased rollout", "Incident management"],
    },
    {
      cat_en: "Tools",
      cat_es: "Herramientas",
      items: ["Jira", "Figma", "Power BI", "Tableau", "Miro", "Confluence"],
    },
  ],

  education: [
    { degree_en: "MSc Banking & Financial Markets",      degree_es: "MSc Banking & Financial Markets",      school: "PUC Valparaíso & Universidad de Cantabria, Spain", year: "2024" },
    { degree_en: "Diploma in Digital Banking & Fintech", degree_es: "Diploma en Banca Digital y Fintech",   school: "Universidad de Cantabria, Spain",                  year: "2023" },
    { degree_en: "Certified Scrum Product Owner (CSPO)", degree_es: "Certified Scrum Product Owner (CSPO)", school: "CertiProf",                                        year: "2022" },
    { degree_en: "Product Designer Certificate",         degree_es: "Certificado en Diseño de Producto",    school: "Coderhouse",                                       year: "2024" },
    { degree_en: "BSc Civil Engineering",                degree_es: "Ingeniería Civil",                     school: "Universidad Privada de Santa Cruz de la Sierra",   year: "2005" },
  ],

  interests: [
    {
      title_en: "Fiction & World-Building",
      title_es: "Ficción y Construcción de Mundos",
      desc_en: "Game of Thrones, Good Omens. Complex systems colliding with human nature — where nobody fully controls the outcome. Sounds familiar.",
      desc_es: "Game of Thrones, Good Omens. Sistemas complejos que chocan con la naturaleza humana — donde nadie controla completamente el resultado. Me suena familiar.",
    },
    {
      title_en: "Films",
      title_es: "Cine",
      desc_en: "Interstellar. Solving an impossible problem with incomplete information, under time pressure, with people depending on the outcome.",
      desc_es: "Interstellar. Resolver un problema imposible con información incompleta, bajo presión de tiempo, con personas dependiendo del resultado.",
    },
    {
      title_en: "Cycling",
      title_es: "Ciclismo",
      desc_en: "Urban routes along the Dublin coast and through Santiago. Between one problem and the next.",
      desc_es: "Rutas urbanas por la costa de Dublín y por Santiago. Entre un problema y el siguiente.",
    },
  ],

}; // end SITE
