// ═══════════════════════════════════════════════════════════════
// PABLO MONTENEGRO — SITE DATA
// Editar este archivo para actualizar cualquier contenido del sitio.
// ═══════════════════════════════════════════════════════════════

window.SITE = {

  name:     "Pablo Montenegro",
  role:     "Senior Product Manager · Payments & Collections",
  tagline:  "I build payment systems that work.",
  location: "Dublin, Ireland",
  email:    "pc.montenegro@gmail.com",
  linkedin: "https://linkedin.com/in/montenegrofp",
  website:  "https://pablomontenegro.ie",
  cv_url:   "/assets/CV_Pablo_Montenegro.pdf",
  photo:    "/assets/pablo-photo.webp",
  seal:     "/assets/pablo-seal.webp",
  sig:      "/assets/pablo-sig.webp",
  logo:     "/assets/logo.webp",

  hero: {
    headline_en: ["Senior Product Manager.", "<em>Payments. Collections. Fintech.</em>"],
    headline_es: ["Senior Product Manager.", "<em>Pagos. Cobranza. Fintech.</em>"],
    quote_en: "10+ years building payment infrastructure, collections systems and banking products at scale. Itaú Chile and independent consulting across Europe and LatAm. Based in Dublin. Available now.",
    quote_es: "10+ años construyendo infraestructura de pagos, sistemas de cobranza y productos bancarios a escala. Itaú Chile y consultoría independiente en Europa y LatAm. Basado en Dublín. Disponible ahora.",
    open_to_en: "Open to relocation · Ireland · Spain · Europe · Remote",
    open_to_es: "Disponible para reubicación · Irlanda · España · Europa · Remoto",
  },

  metrics: [
    { num: "10+",  label_en: "Years · Payments & Banking",  label_es: "Años · Pagos y Banca" },
    { num: "$15M", label_en: "Revenue generated · QR",      label_es: "Ingresos generados · QR" },
    { num: "−30%", label_en: "Complaints reduced · PAC 2.0",label_es: "Quejas reducidas · PAC 2.0" },
    { num: "9",    label_en: "Initiatives delivered",       label_es: "Iniciativas entregadas" },
  ],

  consulting: {
    label_en: "Independent Consulting · 2024–Present",
    label_es: "Consultoría Independiente · 2024–Presente",
    desc_en:  "Four engagements across payment operations, product design, cross-border workflows, and urban mobility — scoped, delivered and measured independently.",
    desc_es:  "Cuatro proyectos en operaciones de pago, diseño de producto, flujos internacionales y movilidad urbana — definidos, entregados y medidos de forma independiente.",
    cases: [
      {
        id: "monevol", num: "01", year: "2024", advisory: true,
        tag_en:   "Product Strategy · UX Research · Personal Finance",
        tag_es:   "Estrategia de Producto · Investigación UX · Finanzas Personales",
        title_en: "Monevol <em>360</em>",
        title_es: "Monevol <em>360</em>",
        desc_en:  "End-to-end product design for a personal finance app targeting underserved users in LatAm. Led full discovery: 34 user interviews across 3 countries, competitive benchmarking, card sorting, MVP scope and 60-screen prototype. Core finding: users needed visibility, not more features.",
        desc_es:  "Diseño de producto end-to-end para una app de finanzas personales dirigida a usuarios desatendidos en LatAm. Lideré el discovery completo: 34 entrevistas en 3 países, benchmarking competitivo, card sorting, scope del MVP y prototipo de 60 pantallas. Hallazgo central: los usuarios necesitaban visibilidad, no más funcionalidades.",
        sepa_en:  "≈ Consumer fintech · payment UX · product strategy",
        sepa_es:  "≈ Fintech consumer · UX de pagos · estrategia de producto",
        metrics:  [
          { num: "98%", label_en: "Usability success rate",  label_es: "Tasa de éxito en usabilidad" },
          { num: "34",  label_en: "User interviews",         label_es: "Entrevistas de usuario" },
          { num: "60+", label_en: "Prototype screens",       label_es: "Pantallas del prototipo" },
        ],
        cta_en: "Full case study →", cta_es: "Caso completo →",
        cta_url: "monevol-case-study.html", vis_type: "monevol",
      },
      {
        id: "remesas", num: "02", year: "2026",
        tag_en:   "Payment Operations · Cross-Border · Workflow Design",
        tag_es:   "Operaciones de Pago · Internacional · Diseño de Flujos",
        title_en: "Cross-Border <em>Payment Operations</em>",
        title_es: "Operaciones de Pago <em>Internacionales</em>",
        desc_en:  "Redesigned client onboarding, transaction tracking, payout controls and reconciliation workflows for a small Europe–Bolivia transfer service. Replaced manual error-prone processes with structured operational flows. Reduced verification workload by 70% at zero tooling cost.",
        desc_es:  "Rediseño de onboarding de clientes, seguimiento de transacciones, controles de pago y flujos de reconciliación para un servicio de transferencias Europa–Bolivia. Reemplazó procesos manuales propensos a errores con flujos operativos estructurados. Redujo la carga de verificación en un 70% sin costo de herramientas.",
        sepa_en:  "≈ Cross-border payment ops · reconciliation · workflow design",
        sepa_es:  "≈ Operaciones de pago internacional · reconciliación · diseño de flujos",
        metrics:  [
          { num: "−70%", label_en: "Verification workload",  label_es: "Carga de verificación" },
          { num: "100%", label_en: "Transactions traceable", label_es: "Transacciones trazables" },
          { num: "€0",   label_en: "Tooling cost",           label_es: "Costo de herramientas" },
        ],
        cta_en: "Full case study →", cta_es: "Caso completo →",
        cta_url: "case-remesas-portfolio.html", vis_type: "remesas",
      },
      {
        id: "karigab", num: "03", year: "2025",
        tag_en:   "Payment Operations · Social Commerce · Retail",
        tag_es:   "Operaciones de Pago · Social Commerce · Retail",
        title_en: "<em>Karigab</em> — Payment & Inventory System",
        title_es: "<em>Karigab</em> — Sistema de Pagos e Inventario",
        desc_en:  "Designed end-to-end payment operations and inventory system for a fashion retailer scaling through TikTok Live. WhatsApp-native checkout, unified physical and digital stock, batch bank reconciliation. Delivered in 7 days. Reduced daily operational workload by 85%.",
        desc_es:  "Sistema completo de operaciones de pago e inventario para tienda de moda que escala por TikTok Live. Checkout por WhatsApp, stock físico y digital unificado, conciliación bancaria por lotes. Entregado en 7 días. Redujo la carga operativa diaria en un 85%.",
        sepa_en:  "≈ Social commerce · payment flows · inventory ops",
        sepa_es:  "≈ Social commerce · flujos de pago · operaciones de inventario",
        metrics:  [
          { num: "−85%", label_en: "Daily operational workload", label_es: "Carga operativa diaria" },
          { num: "7d",   label_en: "Design to delivery",         label_es: "Diseño a entrega" },
          { num: "Bs.0", label_en: "Tooling cost",               label_es: "Costo de herramientas" },
        ],
        cta_en: "Full case study →", cta_es: "Caso completo →",
        cta_url: "karigab-case-study.html", vis_type: "karigab",
      },
      {
        id: "cyclesafe", num: "04", year: "2024–2025", advisory: true,
        tag_en:   "Urban Mobility · Community Product · React Native",
        tag_es:   "Movilidad Urbana · Producto Comunitario · React Native",
        title_en: "<em>CycleSafe</em> — Community Safety Map",
        title_es: "<em>CycleSafe</em> — Mapa Comunitario de Seguridad",
        desc_en:  "Led product from discovery to pilot for a community-powered cycling safety platform in Buenos Aires. Cyclists share real-time route safety data — ciclovías, mixed streets, risk zones — filling the gap that Google Maps and Strava leave. 40 pilot users. Core hypothesis validated: safety is a primary routing criterion. Paused at scale due to relocation to Ireland.",
        desc_es:  "Lideré el producto desde el discovery hasta el piloto para una plataforma de seguridad ciclista impulsada por la comunidad en Buenos Aires. Los ciclistas comparten datos de seguridad en tiempo real — ciclovías, calles mixtas, zonas de riesgo — cubriendo el vacío que dejan Google Maps y Strava. 40 usuarios piloto. Hipótesis central validada: la seguridad es un criterio primario de ruta. Pausado en fase de escala por traslado a Irlanda.",
        sepa_en:  "≈ Community platforms · network effects · mobile product · 0-to-1",
        sepa_es:  "≈ Plataformas comunitarias · efectos de red · producto móvil · 0 a 1",
        metrics:  [
          { num: "40",    label_en: "Pilot users · Buenos Aires", label_es: "Usuarios piloto · Buenos Aires" },
          { num: "React", label_en: "Native · mobile-first stack", label_es: "Native · stack mobile-first" },
          { num: "✓",     label_en: "Safety hypothesis validated", label_es: "Hipótesis de seguridad validada" },
        ],
        cta_en: "Full case study →", cta_es: "Caso completo →",
        cta_url: "cyclesafe-case-study.html", vis_type: "cyclesafe",
      },
    ],
  },

  itau: {
    label_en: "Itaú Bank Chile · 2017–2024",
    label_es: "Itaú Bank Chile · 2017–2024",
    desc_en:  "7 years as Senior PM owning the payments and collections roadmap at Chile's largest private bank. Delivered across infrastructure, recurring collections, mandate digitisation, H2H integrations and operational tooling — in a regulated, enterprise-scale environment.",
    desc_es:  "7 años como Senior PM responsable del roadmap de pagos y cobranza en el banco privado más grande de Chile. Entregué en infraestructura, cobranza recurrente, digitalización de mandatos, integraciones H2H y herramientas operacionales — en un entorno regulado a escala empresarial.",
    cases: [
      {
        id: "pac", num: "04", year: "2021–2022",
        tag_en:   "Collections Platform · Itaú Bank",
        tag_es:   "Plataforma de Cobranza · Itaú Bank",
        title_en: "PAC 2.0 — Automated <em>Collections</em>",
        title_es: "PAC 2.0 — Cobranza <em>Automatizada</em>",
        desc_en:  "Recurring collections failed silently — no retry logic, no failure classification, problems surfaced through complaints. Redesigned the full lifecycle: failure taxonomy, retry logic, operational dashboard and monitoring. Led discovery, API design and phased rollout.",
        desc_es:  "Los cobros recurrentes fallaban en silencio — sin lógica de reintento, sin clasificación de fallas, los problemas surgían por quejas. Rediseñé el ciclo completo: taxonomía de fallas, lógica de reintento, dashboard operacional y monitoreo. Lideré discovery, diseño de API y rollout por fases.",
        sepa_en:  "≈ SEPA Direct Debit · R-message management · collections intelligence",
        sepa_es:  "≈ SEPA Direct Debit · gestión de R-messages · inteligencia de cobranza",
        metrics:  [
          { num: "−30%", label_en: "Customer complaints",    label_es: "Quejas de clientes" },
          { num: "+20%", label_en: "Operational efficiency",  label_es: "Eficiencia operacional" },
          { num: "+15%", label_en: "Collection rate",         label_es: "Tasa de cobro" },
        ],
        cta_en: "Full case study →", cta_es: "Caso completo →",
        cta_url: "itau-pac20.html", vis_type: "pac",
      },
      {
        id: "qr", num: "05", year: "2022–2023",
        tag_en:   "Payment UX · QR Interoperability · Itaú Bank",
        tag_es:   "UX de Pagos · Interoperabilidad QR · Itaú Bank",
        title_en: "QR Interoperability <em>Redesign</em>",
        title_es: "Rediseño de <em>Interoperabilidad QR</em>",
        desc_en:  "Users abandoned at specific steps. Error states confirmed failure without explaining what or why. Mapped every drop-off, ran usability testing, benchmarked against PIX. Redesigned the error language and flow — not just the layout.",
        desc_es:  "Los usuarios abandonaban en pasos específicos. Los estados de error confirmaban la falla sin explicar qué ni por qué. Mapeé cada punto de abandono, realicé pruebas de usabilidad y benchmarking con PIX. Rediseñé el lenguaje de errores y el flujo — no solo la interfaz.",
        sepa_en:  "≈ PIX · Bizum · SEPA Instant · payment flow UX",
        sepa_es:  "≈ PIX · Bizum · SEPA Instant · UX de flujos de pago",
        metrics:  [
          { num: "+25%", label_en: "Adoption increase",   label_es: "Aumento de adopción" },
          { num: "$15M", label_en: "Annual commissions",  label_es: "Comisiones anuales" },
        ],
        cta_en: null, vis_type: "qr",
      },
      {
        id: "epac", num: "06", year: "2021–2022",
        tag_en:   "Mandate Digitisation · Direct Debit · Itaú Bank",
        tag_es:   "Digitalización de Mandatos · Débito Directo · Itaú Bank",
        title_en: "ePAC — Digital <em>Direct Debit</em>",
        title_es: "ePAC — Débito Directo <em>Digital</em>",
        desc_en:  "A 45-day paper mandate process was blocking recurring payment adoption before it started. Led product definition and Forpay partnership to deliver a fully digital mandate platform — reducing activation from weeks to 24 hours.",
        desc_es:  "Un proceso de mandato en papel de 45 días bloqueaba la adopción de pagos recurrentes antes de comenzar. Lideré la definición del producto y la alianza con Forpay para una plataforma de mandatos 100% digital — reduciendo la activación de semanas a 24 horas.",
        sepa_en:  "≈ SEPA mandate e-signature · digital onboarding · recurring payment activation",
        sepa_es:  "≈ Firma electrónica de mandatos SEPA · onboarding digital · activación de pagos recurrentes",
        metrics:  [
          { num: "45d→24h", label_en: "Activation time",     label_es: "Tiempo de activación" },
          { num: "~70%",    label_en: "Customer adoption",    label_es: "Adopción de clientes" },
          { num: "3 mo",    label_en: "End-to-end delivery",  label_es: "Entrega end-to-end" },
        ],
        cta_en: "Full case study →", cta_es: "Caso completo →",
        cta_url: "itau-epac.html", vis_type: "epac",
      },
      {
        id: "multibank", num: "07", year: "2022–2023",
        tag_en:   "B2B Payments · Multi-Bank · Enterprise · Itaú Bank",
        tag_es:   "Pagos B2B · Multibanco · Empresas · Itaú Bank",
        title_en: "Multi-Bank <em>Payment Button</em>",
        title_es: "Botón de Pago <em>Multibanco</em>",
        desc_en:  "Corporate clients needed to receive high-value payments from customers at any Chilean bank without separate integrations per bank. Defined a single access model (API + web portal), led pilot with 3 companies.",
        desc_es:  "Los clientes corporativos necesitaban recibir pagos de alto valor desde cualquier banco chileno sin integraciones separadas por banco. Definí un modelo de acceso único (API + portal web), lideré el piloto con 3 empresas.",
        sepa_en:  "≈ Open Banking payment initiation (PSD2) · B2B payment orchestration",
        sepa_es:  "≈ Iniciación de pagos Open Banking (PSD2) · orquestación de pagos B2B",
        metrics:  [
          { num: "5d→1d",    label_en: "Payment processing", label_es: "Procesamiento de pagos" },
          { num: "CLP 50M+", label_en: "Avg ticket",         label_es: "Ticket promedio" },
          { num: "3 co.",    label_en: "Pilot companies",     label_es: "Empresas piloto" },
        ],
        cta_en: "Full case study →", cta_es: "Caso completo →",
        cta_url: "itau-multibank.html", vis_type: "multibank",
      },
      {
        id: "engine", num: "08", year: "2020–2021",
        tag_en:   "Platform Infrastructure · Notifications · Itaú Bank",
        tag_es:   "Infraestructura · Notificaciones · Itaú Bank",
        title_en: "Bank-Wide <em>Notification Engine</em>",
        title_es: "Motor de <em>Notificaciones</em> Bancario",
        desc_en:  "Legacy system had hard volume limits, no push support and required full rebuild per product. Defined a 3-channel engine (SMS, email, push) with intelligent routing and plug-and-play architecture usable by any team.",
        desc_es:  "El sistema heredado tenía límites de volumen fijos, sin soporte push y requería reconstrucción completa por producto. Definí un motor de 3 canales (SMS, email, push) con enrutamiento inteligente y arquitectura plug-and-play usable por cualquier equipo.",
        sepa_en:  "≈ Payment notification infrastructure · multi-channel delivery",
        sepa_es:  "≈ Infraestructura de notificaciones de pago · entrega multicanal",
        metrics:  [
          { num: "3",  label_en: "Channels unified",    label_es: "Canales unificados" },
          { num: "0",  label_en: "Per-product rebuilds", label_es: "Reconstrucciones por producto" },
        ],
        cta_en: null, vis_type: "engine",
      },
      {
        id: "dashboard", num: "09", year: "2020–2021",
        tag_en:   "Operational Intelligence · Analytics · Itaú Bank",
        tag_es:   "Inteligencia Operacional · Analítica · Itaú Bank",
        title_en: "Collections <em>Monitoring Dashboard</em>",
        title_es: "Dashboard de <em>Monitoreo</em> de Cobranza",
        desc_en:  "Incidents surfaced through complaints — not data. Defined three purpose-built views for three audiences: operations (real-time), commercial (client-level) and product (trends). Reduced incident detection time by 40%.",
        desc_es:  "Los incidentes surgían por quejas, no por datos. Definí tres vistas con propósito específico para tres audiencias: operaciones (tiempo real), comercial (por cliente) y producto (tendencias). Redujo la detección de incidentes en un 40%.",
        sepa_en:  "≈ Payment operations intelligence · SLA monitoring · incident management",
        sepa_es:  "≈ Inteligencia de operaciones de pago · monitoreo de SLA · gestión de incidentes",
        metrics:  [
          { num: "40%", label_en: "Faster incident detection", label_es: "Detección más rápida" },
          { num: "3",   label_en: "Purpose-built views",       label_es: "Vistas especializadas" },
        ],
        cta_en: null, vis_type: "dashboard",
      },
    ],
  },

  products: [
    {
      img: "/assets/prod-1.webp",
      type_en: "Template · Notion / Document",
      type_es: "Plantilla · Notion / Documento",
      title_en: "Fintech Process Documentation Template",
      title_es: "Plantilla de Documentación de Procesos Fintech",
      desc_en: "Standardise how your team documents product decisions, payment flows and operational processes.",
      desc_es: "Estandariza cómo tu equipo documenta decisiones de producto, flujos de pago y procesos operacionales.",
      price: "€19", url: "https://pablomontenegro.gumroad.com/l/vxgcb",
    },
    {
      img: "/assets/prod-2.webp",
      type_en: "Guide · 10 chapters · EN & ES",
      type_es: "Guía · 10 capítulos · EN y ES",
      title_en: "How Payments Actually Work",
      title_es: "Cómo Funcionan Realmente los Pagos",
      desc_en: "A practitioner's guide to payment and collections product management. Written from 10 years of hands-on delivery.",
      desc_es: "Una guía práctica para la gestión de productos de pago y cobranza. Escrita desde 10 años de entrega real.",
      price: "€29", url: "https://pablomontenegro.gumroad.com/l/kqadd",
    },
    {
      img: "/assets/prod-3.webp",
      type_en: "Tool · Excel · EN & ES",
      type_es: "Herramienta · Excel · EN y ES",
      title_en: "Backlog Prioritisation Matrix",
      title_es: "Matriz de Priorización de Backlog",
      desc_en: "Automated weighted scoring model for fintech product teams. 7 decision pillars with MoSCoW filter.",
      desc_es: "Modelo de puntuación ponderada para equipos de producto fintech. 7 pilares de decisión con filtro MoSCoW.",
      price: "€39", url: "https://montenegrofp.gumroad.com/l/BacklogPrioritisationMatrix",
    },
    {
      img: "/assets/prod-4.webp",
      type_en: "Tool · Excel macro · Personal finance",
      type_es: "Herramienta · Macro Excel · Finanzas personales",
      title_en: "Financial Operating System",
      title_es: "Sistema Operativo Financiero",
      desc_en: "Personal finance macro for income, expenses, savings goals and investments. Control without complexity.",
      desc_es: "Macro de finanzas personales para ingresos, gastos, metas de ahorro e inversiones. Control sin complejidad.",
      price: "€19", url: null, coming_soon: true,
    },
  ],

  experience: [
    {
      years: "2024 – Present", company: "Independent Consultant", location: "Dublin, Ireland",
      role_en: "PM Consultant · Payments & Collections",
      role_es: "Consultor PM · Pagos y Cobranza",
      bullets_en: [
        "<strong>Monevol 360 (2024):</strong> Full product lifecycle — 34 user interviews, MVP scope, 60-screen Figma prototype, 98% usability success rate.",
        "<strong>Karigab (2025):</strong> Payment operations and inventory system for social commerce retail. −85% operational workload. Shipped in 7 days.",
        "<strong>Cross-border payment operations (2026):</strong> Workflow redesign for Europe–Bolivia transfer service. Structured onboarding, transaction tracking, payout controls and reconciliation. −70% verification workload.",
        "Ongoing: 500+ annotated training data points for an AI model platform — payment and collections use cases, above 95% accuracy.",
      ],
      bullets_es: [
        "<strong>Monevol 360 (2024):</strong> Ciclo completo de producto — 34 entrevistas, scope del MVP, prototipo Figma de 60 pantallas, 98% de tasa de éxito en usabilidad.",
        "<strong>Karigab (2025):</strong> Sistema de operaciones de pago e inventario para retail de social commerce. −85% de carga operativa. Entregado en 7 días.",
        "<strong>Operaciones de pago internacionales (2026):</strong> Rediseño de flujos para servicio Europa–Bolivia. Onboarding estructurado, seguimiento de transacciones, controles de pago y reconciliación. −70% en carga de verificación.",
        "En curso: 500+ puntos de datos de entrenamiento para una plataforma de IA en casos de uso de pagos y cobranza, con precisión superior al 95%.",
      ],
    },
    {
      years: "2017 – 2024", company: "Itaú Bank Chile", location: "Santiago, Chile",
      role_en: "Senior Product Manager · Payments & Collections",
      role_es: "Senior Product Manager · Pagos y Cobranza",
      bullets_en: [
        "<strong>PAC 2.0:</strong> Redesigned recurring collections lifecycle. −30% complaints, +20% operational efficiency, +15%+ collection rate.",
        "<strong>QR Interoperability:</strong> Mapped drop-off, redesigned error flows, benchmarked against PIX. +25% adoption, $15M annual commission revenue.",
        "<strong>ePAC — Digital Direct Debit:</strong> Mandate activation from 45 days to 24 hours. ~70% adoption. Delivered in 3 months.",
        "<strong>Multi-Bank Payment Button:</strong> Single integration for high-value corporate payments across Chilean banks. Piloted with 3 companies.",
        "<strong>Notification Engine:</strong> 3-channel (SMS, email, push) with intelligent routing and plug-and-play architecture.",
        "<strong>Collections Dashboard:</strong> 3 purpose-built views for operations, commercial and product. 40% faster incident detection.",
      ],
      bullets_es: [
        "<strong>PAC 2.0:</strong> Rediseño del ciclo de cobranza recurrente. −30% quejas, +20% eficiencia operacional, +15%+ tasa de cobro.",
        "<strong>Interoperabilidad QR:</strong> Mapeé abandono, rediseñé flujos de error, benchmarking con PIX. +25% adopción, USD $15M en comisiones anuales.",
        "<strong>ePAC — Débito Directo Digital:</strong> Activación de mandatos de 45 días a 24 horas. ~70% adopción. Entregado en 3 meses.",
        "<strong>Botón de Pago Multibanco:</strong> Integración única para pagos corporativos en bancos chilenos. Piloteado con 3 empresas.",
        "<strong>Motor de Notificaciones:</strong> 3 canales (SMS, email, push) con enrutamiento inteligente y arquitectura plug-and-play.",
        "<strong>Dashboard de Cobranza:</strong> 3 vistas especializadas para operaciones, comercial y producto. 40% más rápida detección de incidentes.",
      ],
    },
    {
      years: "2016 – 2017", company: "SURA Group Chile", location: "Santiago, Chile",
      role_en: "Business Strategy & Client Success Analyst",
      role_es: "Analista de Estrategia de Negocio y Éxito de Clientes",
      bullets_en: ["Performance dashboards and client retention monitoring for a regulated financial services portfolio."],
      bullets_es: ["Dashboards de desempeño y monitoreo de retención de clientes para una cartera de servicios financieros regulados."],
    },
    {
      years: "2012 – 2016", company: "Santander Bank Chile", location: "Santiago, Chile",
      role_en: "Implementation & Process Supervisor — Corporate Cash Management",
      role_es: "Supervisor de Implementación y Procesos — Cash Management Corporativo",
      bullets_en: ["Onboarding, after-sales and SLA monitoring for corporate payment and treasury operations."],
      bullets_es: ["Onboarding, postventa y monitoreo de SLA para operaciones de pago y tesorería corporativa."],
    },
  ],

  writing: [
    {
      type_en: "Industry Analysis · English", type_es: "Análisis de Mercado · Inglés", year: "2024",
      title_en: "Chile's Open Finance Delay: How the Regulatory Pause Could Set Back Innovation",
      title_es: "El Retraso del Open Finance en Chile: Cómo la Pausa Regulatoria Podría Frenar la Innovación",
      desc_en: "Why Chile's Open Finance framework stalled, what it means for payment infrastructure, and why the market cannot afford to wait.",
      desc_es: "Por qué el marco de Open Finance de Chile se detuvo, qué significa para la infraestructura de pagos y por qué el mercado no puede esperar.",
      url: "https://www.linkedin.com/pulse/chiles-open-finance-delay-how-regulatory-pause-back-why-montenegro-sjrle/",
    },
    {
      type_en: "Market Perspective · English", type_es: "Perspectiva de Mercado · Inglés", year: "2024",
      title_en: "Rethinking How We Move Money in Chile",
      title_es: "Repensando Cómo Movemos el Dinero en Chile",
      desc_en: "A practitioner's view on the gap between what payment technology enables and what Chile's regulatory framework currently permits.",
      desc_es: "La visión de un practicante sobre la brecha entre lo que la tecnología de pagos habilita y lo que el marco regulatorio de Chile permite actualmente.",
      url: "https://www.linkedin.com/pulse/rethinking-how-we-move-money-chile-pablo-montenegro-e042c/",
    },
  ],

  recommendations: [
    {
      quote_en: "He connected business and technical worlds effectively — from definition through to delivery.",
      quote_es: "Conectó los mundos de negocio y técnico de forma efectiva — desde la definición hasta la entrega.",
      full_en: "Pablo played a key role implementing recurring payments and digital collections flows, always focused on improving customer experience and operational efficiency. Very organised in product management, with clarity to prioritise, coordinate teams and take initiatives from definition through to delivery.",
      full_es: "Pablo jugó un papel clave en la implementación de pagos recurrentes y flujos de cobranza digital, siempre enfocado en mejorar la experiencia del cliente y la eficiencia operacional. Muy organizado en la gestión de producto, con claridad para priorizar, coordinar equipos y llevar iniciativas desde la definición hasta la entrega.",
      name: "Ignacio Prieto Gana",
      role_en: "CCO at Forpay · Itaú Bank integration partner",
      role_es: "CCO en Forpay · partner de integración Itaú Bank",
      date: "April 2026", url: "https://linkedin.com/in/montenegrofp",
    },
    {
      quote_en: "His contribution was key — always focused on results and excellent at coordinating product and operations.",
      quote_es: "Su contribución fue clave — siempre enfocado en resultados y excelente coordinando producto y operaciones.",
      full_en: "As Product Owner for Collections, Pablo stood out for his business vision, his ability to lead collaboratively and his skill in transforming requirements into concrete, viable solutions that operations could actually run.",
      full_es: "Como Product Owner de Cobranza, Pablo destacó por su visión de negocio, su capacidad de liderar de forma colaborativa y su habilidad para transformar requisitos en soluciones concretas y viables que operaciones pudiera ejecutar.",
      name: "María del Carmen Bini Mattea",
      role_en: "Head of Cash Management · Itaú Chile",
      role_es: "Jefa de Cash Management · Itaú Chile",
      date: "March 2026", url: "https://linkedin.com/in/montenegrofp",
    },
    {
      quote_en: "Outstanding focus on results. He increased client retention by 35% and raised the bar for how we built collections products.",
      quote_es: "Enfoque sobresaliente en resultados. Aumentó la retención de clientes en un 35% y elevó el estándar de cómo construimos productos de cobranza.",
      full_en: "Pablo worked alongside me for 5 years at Itaú Chile. He consistently connected the strategic product vision with the concrete needs of clients and operations — delivering solutions that were both commercially viable and technically sound.",
      full_es: "Pablo trabajó junto a mí durante 5 años en Itaú Chile. Conectó consistentemente la visión estratégica del producto con las necesidades concretas de clientes y operaciones — entregando soluciones viables comercialmente y técnicamente sólidas.",
      name: "Raúl Hidalgo Figueroa",
      role_en: "Digital Transformation Manager · Itaú Chile",
      role_es: "Gerente de Transformación Digital · Itaú Chile",
      date: "March 2026", url: "https://linkedin.com/in/montenegrofp",
    },
    {
      quote_en: "Professionalism, systematic thinking and consistent delivery — he helped us meet our objectives and differentiate from competition.",
      quote_es: "Profesionalismo, pensamiento sistemático y entrega consistente — nos ayudó a alcanzar nuestros objetivos y diferenciarnos de la competencia.",
      full_en: "Pablo was a member of my team, responsible for developing and innovating collections products while maintaining service continuity. He delivered without disruption.",
      full_es: "Pablo era miembro de mi equipo, responsable del desarrollo e innovación de productos de cobranza mientras mantenía la continuidad del servicio. Entregó sin generar disrupciones.",
      name: "Rodrigo Velásquez Velasco",
      role_en: "Product Strategy Manager · direct manager",
      role_es: "Gerente de Estrategia de Producto · manager directo",
      date: "June 2025", url: "https://linkedin.com/in/montenegrofp",
    },
  ],

  skills: [
    {
      cat_en: "Payments & Banking",
      cat_es: "Pagos y Banca",
      items: ["SEPA Direct Debit", "PSD2", "Open Banking", "Recurring collections", "QR payments", "Mandate management", "R-message codes", "H2H integrations", "STP automation"],
    },
    {
      cat_en: "Product Management",
      cat_es: "Gestión de Producto",
      items: ["Product strategy", "Roadmap ownership", "Discovery", "Backlog prioritisation", "MVP definition", "API product management", "Stakeholder management", "Regulated environments"],
    },
    {
      cat_en: "Technical",
      cat_es: "Técnico",
      items: ["REST APIs", "Payment integrations", "Backend systems", "SQL", "Fraud risk mitigation", "System-to-system flows"],
    },
    {
      cat_en: "Research & Design",
      cat_es: "Investigación y Diseño",
      items: ["Design Thinking", "User research", "Figma", "Information architecture", "Usability testing", "Card sorting"],
    },
    {
      cat_en: "Delivery",
      cat_es: "Entrega",
      items: ["Agile · Scrum", "Cross-functional squads", "Phased rollout", "Incident management"],
    },
    {
      cat_en: "Tools",
      cat_es: "Herramientas",
      items: ["Jira", "Figma", "Power BI", "Tableau", "Miro", "Confluence"],
    },
  ],

  education: [
    { degree_en: "MSc Banking & Financial Markets",      degree_es: "MSc Banking & Financial Markets",      school: "PUC Valparaíso & Universidad de Cantabria, Spain", year: "2024" },
    { degree_en: "Diploma in Digital Banking & Fintech", degree_es: "Diploma en Banca Digital y Fintech",   school: "Universidad de Cantabria, Spain",                  year: "2023" },
    { degree_en: "Certified Scrum Product Owner (CSPO)", degree_es: "Certified Scrum Product Owner (CSPO)", school: "CertiProf",                                        year: "2022" },
    { degree_en: "Product Designer Certificate",         degree_es: "Certificado en Diseño de Producto",    school: "Coderhouse",                                       year: "2024" },
    { degree_en: "BSc Civil Engineering",                degree_es: "Ingeniería Civil",                     school: "Universidad Privada de Santa Cruz de la Sierra",   year: "2005" },
  ],

  interests: [
    {
      title_en: "Fiction & World-Building",
      title_es: "Ficción y Construcción de Mundos",
      desc_en: "Game of Thrones, Good Omens. Complex systems colliding with human nature — where nobody fully controls the outcome. Sounds familiar.",
      desc_es: "Game of Thrones, Good Omens. Sistemas complejos que chocan con la naturaleza humana — donde nadie controla completamente el resultado. Me suena familiar.",
    },
    {
      title_en: "Films",
      title_es: "Cine",
      desc_en: "Interstellar. Solving an impossible problem with incomplete information, under time pressure, with people depending on the outcome.",
      desc_es: "Interstellar. Resolver un problema imposible con información incompleta, bajo presión de tiempo, con personas dependiendo del resultado.",
    },
    {
      title_en: "Cycling",
      title_es: "Ciclismo",
      desc_en: "Urban routes along the Dublin coast and through Santiago. Between one problem and the next.",
      desc_es: "Rutas urbanas por la costa de Dublín y por Santiago. Entre un problema y el siguiente.",
    },
  ],

}; // end SITE
