// ═══════════════════════════════════════════════════════════════
// PABLO MONTENEGRO — SITE DATA
// Edit this file to update any content across the entire site.
// No need to touch index.html or section files for content changes.
// ═══════════════════════════════════════════════════════════════

window.SITE = {

  // ── META ──────────────────────────────────────────────────────
  name:     "Pablo Montenegro",
  role:     "Senior Product Manager · Payments & Collections",
  tagline:  "I make money move better.",
  location: "Dublin, Ireland",
  email:    "pc.montenegro@gmail.com",
  linkedin: "https://linkedin.com/in/montenegrofp",
  website:  "https://pablomontenegro.ie",
  cv_url:   "/assets/CV_Pablo_Montenegro.pdf",
  photo:    "/assets/pablo-photo.webp",
  seal:     "/assets/pablo-seal.webp",
  sig:      "/assets/pablo-sig.webp",
  logo:     "/assets/logo.webp",

  // ── HERO ──────────────────────────────────────────────────────
  hero: {
    headline_en: ["I make money", "move <em>better.</em>"],
    headline_es: ["Hago que el dinero", "se mueva <em>mejor.</em>"],
    quote_en: "Most businesses don't know why their payments fail. I've spent 10 years building the systems — and understanding exactly what breaks.",
    quote_es: "La mayoría de los negocios no saben por qué fallan sus pagos. Llevo 10 años construyendo los sistemas — y entendiendo exactamente qué se rompe.",
    open_to_en: "Open to roles · Ireland · Spain · Europe · Remote LatAm",
    open_to_es: "Abierto a roles · Irlanda · España · Europa · Remoto LatAm",
  },

  // ── METRICS ───────────────────────────────────────────────────
  metrics: [
    { num: "10+", label_en: "Years in payments",     label_es: "Años en pagos" },
    { num: "8",   label_en: "Case studies",           label_es: "Casos de estudio" },
    { num: "30%", label_en: "Fewer complaints PAC 2.0", label_es: "Menos quejas PAC 2.0" },
    { num: "$15M",label_en: "Revenue QR integrations", label_es: "Ingresos QR" },
  ],

  // ── WORK — CONSULTING ─────────────────────────────────────────
  consulting: {
    label_en: "Independent Consulting",
    label_es: "Consultoría Independiente",
    desc_en:  "Three end-to-end engagements in payment operations, UX design and cross-border flows — delivered independently, outside any institution.",
    desc_es:  "Tres proyectos end-to-end en operaciones de pago, diseño UX y flujos internacionales — entregados de forma independiente.",
    cases: [
      {
        id:        "monevol",
        num:       "01",
        year:      "2024",
        tag_en:    "UX · Design Thinking · Personal Finance",
        tag_es:    "UX · Design Thinking · Finanzas Personales",
        title_en:  "Monevol <em>360</em>",
        title_es:  "Monevol <em>360</em>",
        desc_en:   "Personal finance app designed from scratch. Full 5-stage Design Thinking process: 34 user interviews across Chile, Colombia and Argentina, competitive benchmarking, card sorting with 11 participants, four wireframe fidelity levels, full UI Kit, and usability testing. The core finding: users didn't want more data — they wanted fewer decisions.",
        desc_es:   "App de finanzas personales diseñada desde cero. 5 etapas completas de Design Thinking: 34 entrevistas en Chile, Colombia y Argentina, benchmarking, card sorting con 11 participantes, cuatro niveles de fidelidad de wireframe, UI Kit completo y pruebas de usabilidad.",
        sepa_en:   "≈ Consumer fintech UX · payment journey design",
        sepa_es:   "≈ UX fintech consumer · diseño de journeys de pago",
        metrics:   [
          { num: "98%", label_en: "Tasks completed",  label_es: "Tareas completadas" },
          { num: "34",  label_en: "User interviews",  label_es: "Entrevistas" },
          { num: "60+", label_en: "Figma frames",     label_es: "Frames Figma" },
        ],
        cta_en:    "Full case study →",
        cta_es:    "Caso completo →",
        cta_url:   "monevol-case-study.html",
        vis_type:  "monevol",
      },
      {
        id:        "remesas",
        num:       "02",
        year:      "2026",
        tag_en:    "Payment Operations · Cross-Border · Fraud Prevention",
        tag_es:    "Operaciones de Pago · Internacional · Prevención de Fraude",
        title_en:  "Cross-Border <em>Transfer Operations</em>",
        title_es:  "Operaciones de <em>Transferencias Internacionales</em>",
        desc_en:   "End-to-end redesign of client onboarding, transaction status tracking, payout controls and internal reconciliation workflows for a small Europe–Bolivia transfer service. Eliminated manual fraud exposure through structured verification. Reduced operational overhead by 70%.",
        desc_es:   "Rediseño end-to-end de onboarding, seguimiento de transacciones, controles de pago y flujos de reconciliación para un servicio de transferencias Europa–Bolivia. Eliminó exposición manual a fraude y redujo carga operativa en 70%.",
        sepa_en:   "≈ Cross-border payment ops · reconciliation design · fraud controls",
        sepa_es:   "≈ Operaciones de pago internacional · reconciliación · controles de fraude",
        metrics:   [
          { num: "−70%", label_en: "Verification time", label_es: "Tiempo verificación" },
          { num: "~45",  label_en: "Tx/month · €150 avg", label_es: "Tx/mes · €150 promedio" },
          { num: "€0",   label_en: "Tooling cost",       label_es: "Costo herramientas" },
        ],
        cta_en:    "Full case study →",
        cta_es:    "Caso completo →",
        cta_url:   "case-remesas-portfolio.html",
        vis_type:  "remesas",
      },
      {
        id:        "karigab",
        num:       "03",
        year:      "2025",
        tag_en:    "Payment Operations · Social Commerce · Retail",
        tag_es:    "Operaciones de Pago · Social Commerce · Retail",
        title_en:  "<em>Karigab</em> — Social-First Retail",
        title_es:  "<em>Karigab</em> — Retail Social-First",
        desc_en:   "Designed end-to-end payment operations and inventory system for a fashion retailer scaling through TikTok Live. WhatsApp-native checkout, unified physical and digital inventory, and bank reconciliation by batch. Reduced daily operational workload by 85% at zero tooling cost, shipped in 7 days.",
        desc_es:   "Sistema completo de pagos e inventario para tienda de moda que escala por TikTok Live. Checkout por WhatsApp, inventario físico y digital unificado, conciliación bancaria por lotes. Reducción del 85% en carga operativa, costo cero, entregado en 7 días.",
        sepa_en:   "≈ Social commerce · WhatsApp payments · inventory ops",
        sepa_es:   "≈ Social commerce · pagos WhatsApp · inventario",
        metrics:   [
          { num: "−85%", label_en: "Workload/day",    label_es: "Carga operativa" },
          { num: "7d",   label_en: "Time to ship",    label_es: "Tiempo entrega" },
          { num: "Bs.0", label_en: "Tooling cost",    label_es: "Costo herramientas" },
        ],
        cta_en:    "Full case study →",
        cta_es:    "Caso completo →",
        cta_url:   "karigab-case-study.html",
        vis_type:  "karigab",
      },
    ],
  },

  // ── WORK — ITAÚ ───────────────────────────────────────────────
  itau: {
    label_en: "Itaú Bank Chile · 2017–2024",
    label_es: "Itaú Bank Chile · 2017–2024",
    desc_en:  "Senior PM owning the roadmap for digital payments and collections at Chile's largest private bank. Six major initiatives across payment infrastructure, recurring collections, H2H integrations and operational tooling.",
    desc_es:  "Senior PM propietario del roadmap de pagos digitales y cobranza en el banco privado más grande de Chile. Seis iniciativas en infraestructura de pagos, cobranza recurrente, integraciónes H2H y herramientas operacionales.",
    cases: [
      {
        id:       "pac",
        num:      "04",
        year:     "2021–2022",
        tag_en:   "Collections Platform · Itaú",
        tag_es:   "Plataforma de Cobranza · Itaú",
        title_en: "PAC 2.0 — Automated <em>Collections</em>",
        title_es: "PAC 2.0 — Cobranza <em>Automatizada</em>",
        desc_en:  "Full redesign of Itaú's recurring payment and collections system. No retry logic, no failure classification, no notifications — collections failed silently. Led discovery, API design, dashboard delivery and phased rollout.",
        desc_es:  "Rediseño completo del sistema de cobranza recurrente de Itaú. Sin lógica de reintentos, sin clasificación de fallas, sin notificaciones. Lideré discovery, diseño de API, dashboard y rollout por fases.",
        sepa_en:  "≈ SEPA Direct Debit mandate management",
        sepa_es:  "≈ Gestión de mandatos SEPA Direct Debit",
        metrics:  [
          { num: "30%",  label_en: "Fewer complaints",  label_es: "Menos quejas" },
          { num: "20%",  label_en: "Efficiency gain",   label_es: "Eficiencia" },
          { num: "15%+", label_en: "Collection rate",   label_es: "Tasa de cobro" },
        ],
        cta_en:   "Full case study →",
        cta_es:   "Caso completo →",
        cta_url:  "itau-pac20.html",
        vis_type: "pac",
      },
      {
        id:       "qr",
        num:      "05",
        year:     "2022–2023",
        tag_en:   "Payment UX · Itaú",
        tag_es:   "UX de Pagos · Itaú",
        title_en: "QR Payment Flow <em>Redesign</em>",
        title_es: "Rediseño de Flujo <em>QR</em>",
        desc_en:  "Users were abandoning at specific steps. Error states confirmed something failed without explaining what. Mapped every drop-off, ran usability testing, benchmarked against PIX. Redesigned the language of errors — not just the layout.",
        desc_es:  "Los usuarios abandonaban en pasos específicos. Los estados de error confirmaban falla sin explicar qué. Mapeé cada abandono, hice pruebas de usabilidad y benchmarking con PIX.",
        sepa_en:  "≈ PIX / Bizum / SEPA Instant error UX",
        sepa_es:  "≈ UX de errores PIX / Bizum / SEPA Instant",
        metrics:  [
          { num: "25%", label_en: "Adoption increase",    label_es: "Adopción" },
          { num: "$15M",label_en: "Commission revenue",   label_es: "Ingresos comisiones" },
        ],
        cta_en:   null,
        vis_type: "qr",
      },
      {
        id:       "epac",
        num:      "06",
        year:     "2021–2022",
        tag_en:   "Digital Mandate Platform · Itaú",
        tag_es:   "Plataforma de Mandatos · Itaú",
        title_en: "ePAC — Digital <em>Direct Debit</em>",
        title_es: "ePAC — Débito Directo <em>Digital</em>",
        desc_en:  "A 45-day paper mandate process was killing sales. Led product definition and Forpay partnership to deliver a fully digital mandate platform — online or max 24 hours activation.",
        desc_es:  "Un proceso de mandato en papel de 45 días estaba matando las ventas. Lideré la definición del producto y la alianza con Forpay para un mandato 100% digital.",
        sepa_en:  "≈ SEPA mandate e-sign & digital onboarding",
        sepa_es:  "≈ Firma digital de mandatos SEPA",
        metrics:  [
          { num: "45d→24h", label_en: "Activation time", label_es: "Activación" },
          { num: "70%",     label_en: "Adoption rate",   label_es: "Adopción" },
        ],
        cta_en:   "Full case study →",
        cta_es:   "Caso completo →",
        cta_url:  "itau-epac.html",
        vis_type: "epac",
      },
      {
        id:       "multibank",
        num:      "07",
        year:     "2022–2023",
        tag_en:   "B2B Infrastructure · Itaú",
        tag_es:   "Infraestructura B2B · Itaú",
        title_en: "Multi-Bank <em>Payment Button</em>",
        title_es: "Botón de Pago <em>Multibanco</em>",
        desc_en:  "High-value corporate payments from any Chilean bank through one integration. Defined dual access models (API + portal), led pilot with 3 companies targeting 40 corporate clients.",
        desc_es:  "Pagos corporativos de alto valor desde cualquier banco chileno a través de una integración. Modelos de acceso duales (API + portal), piloto con 3 empresas.",
        sepa_en:  "≈ Open Banking payment initiation (PSD2)",
        sepa_es:  "≈ Iniciación de pagos Open Banking (PSD2)",
        metrics:  [
          { num: "5d→1d",   label_en: "Payment time",  label_es: "Tiempo de pago" },
          { num: "CLP 50M+",label_en: "Avg ticket",    label_es: "Ticket promedio" },
        ],
        cta_en:   "Full case study →",
        cta_es:   "Caso completo →",
        cta_url:  "itau-multibank.html",
        vis_type: "multibank",
      },
      {
        id:       "engine",
        num:      "08",
        year:     "2020–2021",
        tag_en:   "Platform Infrastructure · Itaú",
        tag_es:   "Infraestructura · Itaú",
        title_en: "Bank-Wide <em>Notification Engine</em>",
        title_es: "Motor de <em>Notificaciones</em>",
        desc_en:  "Legacy system had hard volume caps and no push support. A direct debit only works if the user knows it's coming. Defined 3-channel engine (SMS, email, push) with intelligent routing and bank-wide plug-and-play architecture.",
        desc_es:  "El sistema legacy tenía límites de volumen y sin soporte push. Definí motor de 3 canales (SMS, email, push) con enrutamiento inteligente y arquitectura plug-and-play.",
        sepa_en:  "≈ Multi-channel payment notification infrastructure",
        sepa_es:  "≈ Infraestructura de notificaciones de pago multicanal",
        metrics:  [
          { num: "3",       label_en: "Channels unified", label_es: "Canales unificados" },
          { num: "Bank-wide",label_en: "Architecture",   label_es: "Arquitectura" },
        ],
        cta_en:   null,
        vis_type: "engine",
      },
      {
        id:       "dashboard",
        num:      "09",
        year:     "2020–2021",
        tag_en:   "Product Analytics · Itaú",
        tag_es:   "Analítica de Producto · Itaú",
        title_en: "Collections <em>Monitoring Dashboard</em>",
        title_es: "Dashboard de <em>Monitoreo</em>",
        desc_en:  "Incidents were identified through complaints, not data. Defined three distinct dashboard views — operational (real-time), commercial (client-level) and product (trends) — for different audiences making decisions at different speeds.",
        desc_es:  "Los incidentes se identificaban por quejas, no por datos. Definí tres vistas: operacional (tiempo real), comercial (nivel cliente) y producto (tendencias).",
        sepa_en:  "≈ Payment operations intelligence & SLA monitoring",
        sepa_es:  "≈ Inteligencia operacional y monitoreo de SLA",
        metrics:  [
          { num: "40%", label_en: "Faster detection", label_es: "Detección más rápida" },
          { num: "3",   label_en: "Audience views",   label_es: "Vistas por audiencia" },
        ],
        cta_en:   null,
        vis_type: "dashboard",
      },
    ],
  },

  // ── PRODUCTS ──────────────────────────────────────────────────
  products: [
    {
      img:      "/assets/prod-1.webp",
      type_en:  "Template · Notion / Document",
      type_es:  "Plantilla · Notion / Documento",
      title_en: "Fintech Process Documentation Template",
      title_es: "Plantilla de Documentación de Procesos",
      desc_en:  "Standardise how your team documents product decisions, payment flows, and operational processes.",
      desc_es:  "Estandariza cómo tu equipo documenta decisiones de producto, flujos de pago y procesos operacionales.",
      price:    "€19",
      url:      "https://pablomontenegro.gumroad.com/l/vxgcb",
    },
    {
      img:      "/assets/prod-2.webp",
      type_en:  "Guide · 10 chapters · EN & ES",
      type_es:  "Guía · 10 capítulos · EN & ES",
      title_en: "How Payments Actually Work",
      title_es: "Cómo Funcionan Realmente los Pagos",
      desc_en:  "The practitioner guide to building payment and collections products.",
      desc_es:  "La guía práctica para construir productos de pago y cobranza.",
      price:    "€29",
      url:      "https://pablomontenegro.gumroad.com/l/kqadd",
    },
    {
      img:      "/assets/prod-3.webp",
      type_en:  "Tool · Excel · EN & ES",
      type_es:  "Herramienta · Excel · EN & ES",
      title_en: "Backlog Prioritisation Matrix",
      title_es: "Matriz de Priorización de Backlog",
      desc_en:  "Automated weighted scoring model for fintech product teams. 7 pillars with MoSCoW filter.",
      desc_es:  "Modelo de puntuación ponderada automatizada para equipos de producto fintech.",
      price:    "€39",
      url:      "https://montenegrofp.gumroad.com/l/BacklogPrioritisationMatrix",
    },
    {
      img:      "/assets/prod-4.webp",
      type_en:  "Tool · Excel macro · Personal finance",
      type_es:  "Herramienta · Excel macro · Finanzas personales",
      title_en: "Financial Operating System",
      title_es: "Sistema Operativo Financiero",
      desc_en:  "Personal finance macro for real control over your money. Income, expenses, savings goals, investments.",
      desc_es:  "Macro de finanzas personales para control real del dinero. Ingresos, gastos, objetivos, inversiones.",
      price:    "€19",
      url:      null,
      coming_soon: true,
    },
  ],

  // ── EXPERIENCE ────────────────────────────────────────────────
  experience: [
    {
      years:    "2024 – Present",
      company:  "Independent Consultant",
      location: "Dublin, Ireland",
      role_en:  "Payments & Collections PM Consultant",
      role_es:  "Consultor PM — Pagos y Cobranza",
      bullets_en: [
        "Designed full product lifecycle for <strong>Monevol 360</strong> — 34 user interviews, 11-participant card sort, 60-frame Figma prototype, 98% usability task success.",
        "<strong>Karigab</strong> — end-to-end payment operations and inventory system for TikTok Live retail (2025). −85% operational workload, Bs.0 tooling cost, shipped in 7 days.",
        "Cross-border payment operations redesign for Europe–Bolivia transfer service (2026) — onboarding, tracking, payout controls and reconciliation. Eliminated manual fraud exposure, −70% overhead.",
        "500+ annotated data points for AI model training platform — payment and collections use cases at above 95% accuracy.",
      ],
      bullets_es: [
        "Diseño del ciclo completo de producto para <strong>Monevol 360</strong> — 34 entrevistas, card sort 11 participantes, prototipo Figma 60 pantallas, 98% éxito en usabilidad.",
        "<strong>Karigab</strong> — sistema end-to-end de pagos e inventario para retail por TikTok Live. −85% carga operativa, Bs.0 costo de herramientas, entregado en 7 días.",
        "Rediseño de operaciones de pago internacional para servicio Europa–Bolivia — onboarding, seguimiento, controles de pago y reconciliación. Eliminó exposición a fraude, −70% carga.",
        "500+ puntos de datos anotados para plataforma de entrenamiento de IA — casos de uso de pagos con precisión superior al 95%.",
      ],
    },
    {
      years:    "2017 – 2024",
      company:  "Itaú Bank Chile",
      location: "Santiago, Chile",
      role_en:  "Senior PM · Payments & Collections",
      role_es:  "Senior PM · Pagos y Cobranza",
      bullets_en: [
        "<strong>PAC 2.0:</strong> −30% customer complaints, +20% operational efficiency, +15%+ collection rate through mandate lifecycle redesign and retry logic.",
        "<strong>QR Interoperability:</strong> +25% digital payment adoption; $15M annual commission revenue; PIX-benchmarked error redesign.",
        "<strong>ePAC — Digital Direct Debit:</strong> mandate activation 45 days → 24 hours; 70% end-user subscription rate; 3-month delivery.",
        "<strong>H2H Integration:</strong> replaced manual file ingestion with automated system-to-system flows.",
        "<strong>Monitoring Dashboard:</strong> 40% faster incident detection across 3 audience views.",
      ],
      bullets_es: [
        "<strong>PAC 2.0:</strong> −30% quejas, +20% eficiencia operacional, +15%+ tasa de cobro mediante rediseño del ciclo de mandatos.",
        "<strong>Interoperabilidad QR:</strong> +25% adopción; USD $15M en comisiones; rediseño de errores referenciado en PIX.",
        "<strong>ePAC:</strong> activación de mandatos de 45 días → 24 horas; 70% tasa de suscripción; entrega en 3 meses.",
        "<strong>Integración H2H:</strong> reemplazó ingesta manual de archivos por flujos sistema-a-sistema automatizados.",
        "<strong>Dashboard de Monitoreo:</strong> 40% más rápida detección de incidentes en 3 vistas diferenciadas.",
      ],
    },
    {
      years:    "2016 – 2017",
      company:  "SURA Group Chile",
      location: "Santiago, Chile",
      role_en:  "Business Strategy & Client Success Analyst",
      role_es:  "Analista de Estrategia y Éxito de Clientes",
      bullets_en: ["Portfolio performance dashboards and client retention monitoring across a regulated financial services client base."],
      bullets_es: ["Dashboards de desempeño de cartera y monitoreo de retención de clientes en servicios financieros regulados."],
    },
    {
      years:    "2012 – 2016",
      company:  "Santander Bank Chile",
      location: "Santiago, Chile",
      role_en:  "Implementation & Process Supervisor — Corporate Cash Management",
      role_es:  "Supervisor de Implementación — Cash Management Corporativo",
      bullets_en: ["Corporate client onboarding, after-sales services and SLA monitoring for payment and treasury operations."],
      bullets_es: ["Onboarding de clientes corporativos, servicios postventa y monitoreo de SLAs para operaciones de pago y tesorería."],
    },
  ],

  // ── WRITING ───────────────────────────────────────────────────
  writing: [
    {
      type_en:  "Industry Analysis · English",
      type_es:  "Análisis de Mercado · Inglés",
      year:     "2024",
      title_en: "Chile's Open Finance Delay: How the Regulatory Pause Could Set Back Innovation",
      title_es: "El Retraso del Open Finance en Chile",
      desc_en:  "Analysis of why Chile's Open Finance regulatory framework stalled, what it means for payment innovation, and why the market cannot afford to wait.",
      desc_es:  "Análisis del estancamiento del marco regulatorio de Open Finance en Chile y su impacto en la innovación en pagos.",
      url:      "https://www.linkedin.com/pulse/chiles-open-finance-delay-how-regulatory-pause-back-why-montenegro-sjrle/",
    },
    {
      type_en:  "Market Perspective · English",
      type_es:  "Perspectiva de Mercado · Inglés",
      year:     "2024",
      title_en: "Rethinking How We Move Money in Chile",
      title_es: "Repensando Cómo Movemos el Dinero en Chile",
      desc_en:  "A practitioner's perspective on payment infrastructure evolution — the gap between what the technology allows and what the regulatory framework permits.",
      desc_es:  "Perspectiva de un practicante sobre la evolución de la infraestructura de pagos en Chile.",
      url:      "https://www.linkedin.com/pulse/rethinking-how-we-move-money-chile-pablo-montenegro-e042c/",
    },
  ],

  // ── RECOMMENDATIONS ───────────────────────────────────────────
  recommendations: [
    {
      quote_en: "He connected business and technical worlds effectively — from definition through to delivery.",
      quote_es: "Conectó los mundos de negocio y técnico de forma efectiva — desde la definición hasta la entrega.",
      full_en:  "Pablo played a key role implementing recurring payments and digital collections flows, always focused on improving customer experience and operational efficiency. Very organised in product management, with clarity to prioritise, coordinate teams and take initiatives from definition through to delivery.",
      full_es:  "Pablo jugó un papel clave en la implementación de pagos recurrentes y flujos de cobranza digital, siempre enfocado en mejorar la experiencia del cliente y la eficiencia operacional.",
      name:     "Ignacio Prieto Gana",
      role_en:  "CCO at Forpay · Itaú integration",
      role_es:  "CCO en Forpay · integración Itaú",
      date:     "April 2026",
      url:      "https://linkedin.com/in/montenegrofp",
    },
    {
      quote_en: "His contribution was key — always focused on results and excellent coordination between product and operations.",
      quote_es: "Su contribución fue clave — siempre enfocado en resultados y excelente coordinación entre producto y operaciones.",
      full_en:  "As Product Owner for Collections, Pablo stood out for his business vision, his ability to lead collaboratively and his skill in transforming needs into concrete, viable solutions.",
      full_es:  "Como Product Owner de Cobranza, Pablo destacó por su visión de negocio y su habilidad para transformar necesidades en soluciones concretas y viables.",
      name:     "María del Carmen Bini Mattea",
      role_en:  "Head of Dept., Cash Management · Itaú Chile",
      role_es:  "Jefa de Área, Cash Management · Itaú Chile",
      date:     "March 2026",
      url:      "https://linkedin.com/in/montenegrofp",
    },
    {
      quote_en: "Outstanding leadership and a decisive focus on results. He increased client retention by 35%.",
      quote_es: "Liderazgo sobresaliente y un enfoque decisivo en resultados. Aumentó la retención de clientes en un 35%.",
      full_en:  "Pablo worked alongside me for 5 years at Itaú Chile. He connected the strategic product vision for collections with the concrete needs of clients, ensuring high-impact solutions.",
      full_es:  "Pablo trabajó conmigo durante 5 años en Itaú Chile. Conectó la visión estratégica de producto con las necesidades concretas de los clientes.",
      name:     "Raúl Hidalgo Figueroa",
      role_en:  "Digital Transformation · Itaú Chile",
      role_es:  "Transformación Digital · Itaú Chile",
      date:     "March 2026",
      url:      "https://linkedin.com/in/montenegrofp",
    },
    {
      quote_en: "He stood out for his professionalism, systematic approach and focus — enabling us to meet planned objectives and stand out from competition.",
      quote_es: "Destacó por su profesionalismo, enfoque sistemático y resultados — permitiéndonos alcanzar los objetivos planificados.",
      full_en:  "Pablo was a member of my team, responsible for developing and innovating collections products while maintaining service continuity.",
      full_es:  "Pablo era miembro de mi equipo, responsable del desarrollo e innovación de productos de cobranza.",
      name:     "Rodrigo Velásquez Velasco",
      role_en:  "Product Strategy Manager · managed Pablo directly",
      role_es:  "Gerente de Estrategia de Producto · gestionó a Pablo directamente",
      date:     "June 2025",
      url:      "https://linkedin.com/in/montenegrofp",
    },
  ],

  // ── SKILLS ────────────────────────────────────────────────────
  skills: [
    {
      cat_en: "Payments domain",
      cat_es: "Dominio de pagos",
      items: ["SEPA Direct Debit","PSD2","Open Banking","Recurring collections","QR payments","Mandate management","R-message codes","H2H integrations"],
    },
    {
      cat_en: "Product",
      cat_es: "Producto",
      items: ["Product strategy","Roadmap ownership","Discovery","Backlog prioritisation","MVP definition","API Product Management","Stakeholder management"],
    },
    {
      cat_en: "Technical",
      cat_es: "Técnico",
      items: ["REST APIs","Payment integrations","Backend systems","SQL","Fraud risk mitigation","STP automation"],
    },
    {
      cat_en: "Design",
      cat_es: "Diseño",
      items: ["Design Thinking","User research","Figma prototyping","Information architecture","Usability testing"],
    },
    {
      cat_en: "Delivery",
      cat_es: "Entrega",
      items: ["Agile · Scrum","Cross-functional squads","Regulated environments","Incident management"],
    },
    {
      cat_en: "Tools",
      cat_es: "Herramientas",
      items: ["Jira","Figma","Power BI","Tableau","Miro","Confluence"],
    },
  ],

  // ── EDUCATION ─────────────────────────────────────────────────
  education: [
    { degree_en: "MSc Banking & Financial Markets", degree_es: "MSc Banking & Financial Markets", school: "PUC Valparaíso & Universidad de Cantabria, Spain", year: "2024" },
    { degree_en: "Diploma in Digital Banking & Fintech", degree_es: "Diploma en Banca Digital y Fintech", school: "Universidad de Cantabria, Spain", year: "2023" },
    { degree_en: "Certified Scrum Product Owner (CSPO)", degree_es: "Certified Scrum Product Owner (CSPO)", school: "CertiProf", year: "2022" },
    { degree_en: "Product Designer Certificate", degree_es: "Certificado en Diseño de Producto", school: "Coderhouse", year: "2024" },
    { degree_en: "BSc Civil Engineering", degree_es: "Ingeniería Civil", school: "Universidad Privada de Santa Cruz de la Sierra", year: "2005" },
  ],

  // ── INTERESTS ─────────────────────────────────────────────────
  interests: [
    {
      title_en: "Fiction Literature",
      title_es: "Literatura de Ficción",
      desc_en:  "Epic world-building with real consequences — Game of Thrones, Good Omens. Stories where complex systems collide with human nature and nobody fully controls the outcome. Payments, basically.",
      desc_es:  "Construcción épica de mundos con consecuencias reales — Game of Thrones, Good Omens. Historias donde sistemas complejos chocan con la naturaleza humana. Los pagos, básicamente.",
    },
    {
      title_en: "Films",
      title_es: "Cine",
      desc_en:  "Interstellar. A film about solving an impossible problem with incomplete information, under time pressure, with people depending on you getting it right. I relate to that professionally.",
      desc_es:  "Interstellar. Una película sobre resolver un problema imposible con información incompleta, bajo presión de tiempo. Me identifico profesionalmente.",
    },
    {
      title_en: "Cycling",
      title_es: "Ciclismo",
      desc_en:  "Urban cycling along the Dublin coast and through Santiago. It's how I clear my head between one problem and the next.",
      desc_es:  "Ciclismo urbano por la costa de Dublín y Santiago. Es como despejo la cabeza entre un problema y el siguiente.",
    },
  ],

}; // end SITE
